export const cities = [
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    state: 'CA',
    stateFullName: 'California',
    headline: 'Clinical case management rooted in Los Angeles, serving clients everywhere.',
    intro: 'Holistic Solutions Case Management was founded in Los Angeles, CA — one of the most complex behavioral health markets in the country. We know the local providers, the treatment landscape, and the resources available here. Whether you\'re navigating a substance use crisis, a first psychiatric break, or a need for coordinated ongoing care, our team is here to help you find the right path forward.',
    localNote: 'We work with individuals and families throughout the greater Los Angeles area, including Beverly Hills, Santa Monica, Pasadena, Long Beach, and the San Fernando Valley.',
  },
  {
    slug: 'new-york',
    name: 'New York',
    state: 'NY',
    stateFullName: 'New York',
    headline: 'Clinical case management for individuals and families in New York.',
    intro: 'Navigating the behavioral health system in New York City can be overwhelming. The options are endless but finding the right fit — a provider who truly specializes in what you\'re facing — takes expertise and connections most people don\'t have. Holistic Solutions Case Management brings masters-level clinical coordination to individuals and families across New York, ensuring you get care that actually matches your needs.',
    localNote: 'We serve clients throughout the New York metro area, including Manhattan, Brooklyn, Queens, the Bronx, Staten Island, and surrounding suburbs.',
  },
  {
    slug: 'miami',
    name: 'Miami',
    state: 'FL',
    stateFullName: 'Florida',
    headline: 'Clinical case management for individuals and families in Miami.',
    intro: 'Florida has one of the largest concentrations of treatment programs in the country — which means finding the right one requires expert guidance. Holistic Solutions Case Management helps individuals and families in Miami navigate substance use, mental health, and co-occurring disorder treatment with the kind of clinical rigor and personal advocacy that makes a real difference.',
    localNote: 'We serve clients throughout the Miami metro area, including Miami Beach, Coral Gables, Fort Lauderdale, Boca Raton, and Palm Beach.',
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'IL',
    stateFullName: 'Illinois',
    headline: 'Clinical case management for individuals and families in Chicago.',
    intro: 'Getting the right behavioral health care in Chicago shouldn\'t require navigating a fragmented, confusing system alone. Holistic Solutions Case Management provides masters-level clinical coordination for substance use, mental health, and co-occurring disorders — working alongside individuals and families to build care plans that actually fit, and staying involved from first contact through long-term recovery.',
    localNote: 'We serve clients throughout the Chicago metro area, including the North Shore, Naperville, Evanston, Oak Park, and surrounding communities.',
  },
  {
    slug: 'houston',
    name: 'Houston',
    state: 'TX',
    stateFullName: 'Texas',
    headline: 'Clinical case management for individuals and families in Houston.',
    intro: 'Houston\'s size and diversity mean that behavioral health needs vary enormously — and cookie-cutter treatment rarely works. Holistic Solutions Case Management brings individualized clinical expertise to individuals and families in Houston navigating substance use, mental health crises, and complex co-occurring presentations. We assess the full picture and coordinate care that actually addresses it.',
    localNote: 'We serve clients throughout the Houston metro area, including The Woodlands, Sugar Land, Katy, Pearland, and surrounding communities.',
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'AZ',
    stateFullName: 'Arizona',
    headline: 'Clinical case management for individuals and families in Phoenix.',
    intro: 'Arizona has a significant treatment and recovery community, but finding the right clinical fit requires more than a Google search. Holistic Solutions Case Management works with individuals and families in Phoenix to assess complex behavioral health needs, identify the right providers, and stay involved through every step of the care process.',
    localNote: 'We serve clients throughout the Phoenix metro area, including Scottsdale, Tempe, Mesa, Chandler, and Tucson.',
  },
  {
    slug: 'las-vegas',
    name: 'Las Vegas',
    state: 'NV',
    stateFullName: 'Nevada',
    headline: 'Clinical case management for individuals and families in Las Vegas.',
    intro: 'Las Vegas presents a unique and often challenging environment for individuals navigating substance use and mental health. Holistic Solutions Case Management — founded and led by a Nevada-rooted clinician — understands the local context and brings individualized, high-quality behavioral health coordination to individuals and families across the Las Vegas valley.',
    localNote: 'We serve clients throughout Las Vegas and the surrounding area, including Henderson, Summerlin, North Las Vegas, and Boulder City.',
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco',
    state: 'CA',
    stateFullName: 'California',
    headline: 'Clinical case management for individuals and families in San Francisco.',
    intro: 'The Bay Area has significant behavioral health resources — but also significant barriers to accessing the right ones. Holistic Solutions Case Management helps individuals and families in San Francisco cut through the noise, connect with genuinely specialized providers, and build coordinated care plans that address the full clinical picture.',
    localNote: 'We serve clients throughout the Bay Area, including Oakland, Berkeley, San Jose, Marin County, and the Peninsula.',
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    state: 'WA',
    stateFullName: 'Washington',
    headline: 'Clinical case management for individuals and families in Seattle.',
    intro: 'Seattle\'s behavioral health landscape is vast but difficult to navigate, especially for complex presentations involving substance use, psychosis, or co-occurring disorders. Holistic Solutions Case Management brings masters-level clinical expertise to individuals and families in the Pacific Northwest — providing the kind of coordinated, personalized care advocacy that leads to real outcomes.',
    localNote: 'We serve clients throughout the Seattle metro area, including Bellevue, Tacoma, Kirkland, Redmond, and surrounding communities.',
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    state: 'TX',
    stateFullName: 'Texas',
    headline: 'Clinical case management for individuals and families in Dallas.',
    intro: 'Whether you\'re in Dallas dealing with a substance use crisis, a mental health emergency, or the challenge of coordinating care for a complex co-occurring presentation, Holistic Solutions Case Management can help. Our masters-level clinicians assess the full picture, identify the right providers from our national network, and stay with you through the process.',
    localNote: 'We serve clients throughout the Dallas–Fort Worth metro area, including Plano, Frisco, Irving, Arlington, and Fort Worth.',
  },
]

export function getCityBySlug(slug) {
  return cities.find((c) => c.slug === slug) || null
}
