export const PHONE_DISPLAY = '(702) 494-7641'
export const PHONE_HREF = 'tel:+17024947641'
export const EMAIL = 'info@hscasemanagement.com'
export const SITE_URL = 'https://hscasemanagement.com'
export const BUSINESS_NAME = 'Holistic Solutions Case Management'
export const HOURS = 'Monday – Friday, 8am – 6pm'
