export const posts = [
  {
    slug: 'marijuana-psychosis-what-families-need-to-know',
    title: 'Marijuana and Psychosis: What Families Need to Know',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'One of the most common calls I receive from families: "He\'s been smoking weed heavily for years and now he\'s saying things that don\'t make sense. Could the marijuana be causing this?" The short answer is: possibly, yes. Here\'s what every family navigating this situation needs to understand.',
    metaDescription: 'Heavy cannabis use is increasingly linked to psychosis and schizophrenia. What families need to know — and how clinical case management can help.',
    date: '2026-03-01',
    category: 'Clinical Insights',
    image: '/blog-marijuana-psychosis.jpg',
    imageAlt: 'Man sitting alone on a sofa with his head in his hand, appearing distressed',
    relatedServices: ['mental-health', 'co-occurring-disorders', 'substance-use'],
    body: [
      { type: 'p', text: 'One of the most common calls I receive from families goes something like this: "He\'s been smoking weed heavily for years and now he\'s saying things that don\'t make sense. Could the marijuana be causing this?"' },
      { type: 'p', text: 'The short answer is: possibly, yes. And the longer answer is one every family navigating this situation needs to understand.' },
      { type: 'h2', text: 'The Research Is Clear. And Getting Clearer.' },
      { type: 'p', text: 'For years, the cannabis-psychosis connection was debated. That debate has largely been settled. A 2024 umbrella review published in Psychiatry Research analyzing 32 systematic reviews and meta-analyses found that cannabis use is consistently associated with earlier onset of psychosis and increased risk of psychotic-like experiences. A separate 2025 study published in JAMA Psychiatry identified a shared dopamine pathway as a likely biological mechanism, with heavy cannabis use elevating dopamine activity in patterns that mirror early-stage schizophrenia.' },
      { type: 'p', text: 'Perhaps most concerning for clinical practice: a 2025 University of Colorado review of nearly 100 studies comprising over 221,000 participants found that high-potency cannabis products, including concentrates, dabs, and high-THC flower, show particularly strong links to psychosis and schizophrenia. This matters because the cannabis available today is dramatically more potent than what existed even ten years ago.' },
      { type: 'h2', text: 'Cannabis-Induced Psychosis vs. An Underlying Disorder' },
      { type: 'p', text: 'This is the clinical distinction that matters most, and it requires a trained clinician to assess properly.' },
      { type: 'p', text: 'Cannabis-induced psychosis typically emerges during or shortly after heavy use and can resolve with abstinence, though not always, and not always quickly. What complicates the picture significantly is that cannabis use can also unmask an underlying psychotic disorder in someone who was already genetically vulnerable. In those cases, stopping cannabis doesn\'t stop the psychosis. It simply removes one accelerant.' },
      { type: 'p', text: 'A 2025 systematic review published in the British Journal of Psychiatry added another layer of complexity: psychosis can also emerge during cannabis withdrawal. Abrupt cessation of heavy, long-term use can trigger acute psychotic symptoms in some individuals, meaning that simply getting someone to stop without clinical support in place can itself become a crisis.' },
      { type: 'p', text: 'This is why assessment matters. Not every case of marijuana-related psychosis is the same. The trajectory, severity, and appropriate intervention depend heavily on the individual\'s psychiatric history, family history, pattern of use, and what persists after abstinence.' },
      { type: 'h2', text: 'What Families Are Often Getting Wrong' },
      { type: 'p', text: 'The two most common mistakes I see families make:' },
      { type: 'p', text: 'First, assuming it\'s just the weed and waiting it out. Sometimes this works. Often it doesn\'t, and time lost in untreated psychosis has real consequences for long-term outcomes. Early intervention produces significantly better prognoses than delayed intervention.' },
      { type: 'p', text: 'Second, getting their loved one to stop using abruptly without clinical support in place. Given what we now know about withdrawal-associated psychosis, this can worsen the situation without the right clinical framework around it.' },
      { type: 'h2', text: 'What Clinical Case Management Looks Like in These Situations' },
      { type: 'p', text: 'When families call me about a loved one showing signs of psychosis alongside heavy cannabis use, the first thing I do is help them understand what they\'re actually looking at. Is this acute intoxication? Cannabis-induced psychosis? An emerging psychotic disorder that cannabis has been masking or accelerating? The answer changes everything: the level of care needed, the type of program, the clinical team required.' },
      { type: 'p', text: 'From there, case management involves coordinating a proper psychiatric evaluation, identifying treatment settings equipped to handle co-occurring substance use and psychotic presentations simultaneously, and building the kind of wraparound support that keeps the person stable through the process. Most standard treatment programs are not set up to handle this combination well. Finding the ones that are is the work.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'If your loved one has been using marijuana heavily, especially high-potency products, and you\'re seeing paranoia, disorganized thinking, beliefs that seem disconnected from reality, or behavior that feels frightening or unfamiliar, don\'t wait. These presentations are treatable. But they require clinical eyes, not just time.' },
      { type: 'p', text: 'The research on cannabis and psychosis has never been stronger. The clinical pathways have never been clearer. And the families navigating this don\'t have to do it alone.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If you\'re concerned about a loved one, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'Groening et al. (2024). Systematic evidence map of cannabis use and psychosis-related outcomes. Psychiatry Research, 331. doi:10.1016/j.psychres.2023.115626',
      'Ahrens et al. (2025). Convergence of cannabis and psychosis on the dopamine system. JAMA Psychiatry. doi:10.1001/jamapsychiatry.2025.0432',
      'University of Colorado Anschutz (2025). High-concentration THC products and mental health outcomes. Annals of Internal Medicine.',
      'Basu et al. (2025). Cannabis and psychopathology: 2024 snapshot. PMC/NIH. PMID: PMC12032589',
      'Cannabis withdrawal-associated psychosis: systematic review and case series. British Journal of Psychiatry (2025). PMC7617269',
    ],
  },

  {
    slug: 'when-a-loved-one-refuses-treatment',
    title: 'When a Loved One Refuses Treatment: What Families Can Actually Do',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'The call I receive most often isn\'t "we need help." It\'s "we need help, but he won\'t go." Refusal is the norm, not the exception. And it has evidence-based solutions most families have never heard of.',
    metaDescription: 'When a loved one refuses treatment, families feel stuck. What actually works — CRAFT, motivational interviewing, and when to consider intervention.',
    date: '2026-03-02',
    category: 'Family Guidance',
    image: null,
    relatedServices: ['intervention-services', 'substance-use', 'mental-health'],
    body: [
      { type: 'p', text: 'The call I receive most often isn\'t "we need help." It\'s "we need help, but he won\'t go."' },
      { type: 'p', text: 'Refusal is the norm, not the exception. Most people with addiction or untreated mental illness don\'t arrive at treatment willingly. Understanding why, and knowing what to do about it, changes everything for the families involved.' },
      { type: 'h2', text: 'Why Refusal Isn\'t Simply Defiance' },
      { type: 'p', text: 'When a loved one refuses help, the most painful interpretation is that they don\'t care: about their health, their family, or their future. That interpretation is almost always wrong.' },
      { type: 'p', text: 'There\'s a clinical concept called anosognosia, an impaired awareness of one\'s own illness, that affects a significant portion of people with serious mental illness and active addiction. It\'s not denial in the psychological sense. It\'s a neurological feature of the illness itself. The brain\'s capacity for self-assessment is compromised by the very condition that needs treatment. Asking someone in this state to accurately evaluate their own need for help is like asking someone with a broken thermometer to take their own temperature.' },
      { type: 'p', text: 'Ambivalence plays a major role as well. Motivational Interviewing (MI), developed by psychologists William Miller and Stephen Rollnick, is built on the recognition that people in the contemplation stage of change hold genuinely competing motivations: they both want to change and don\'t want to change, often simultaneously. That ambivalence isn\'t a character flaw. It\'s a predictable psychological state, and it has an evidence-based clinical response.' },
      { type: 'h2', text: 'What Most Families Try (And Why It Often Backfires)' },
      { type: 'p', text: 'The most common approaches families take are ultimatums, pleading, and researching treatment programs the person hasn\'t agreed to attend. These approaches come from love. They rarely produce the desired outcome.' },
      { type: 'p', text: 'Ultimatums can be effective, but only when they\'re backed by genuine, clearly-communicated consequences delivered calmly, not in the heat of a crisis. An ultimatum issued in desperation, without a plan, often damages trust without changing behavior.' },
      { type: 'p', text: 'Less obvious is how certain protective behaviors, like managing consequences, covering for a loved one, or keeping the peace at all costs, can reduce the motivation to seek change. This isn\'t a judgment. It\'s a pattern that has a name and an evidence-based alternative.' },
      { type: 'h2', text: 'CRAFT: The Approach Most Families Have Never Heard Of' },
      { type: 'p', text: 'Community Reinforcement and Family Training (CRAFT) is an evidence-based approach developed by Dr. Robert Meyers that specifically helps family members influence a resistant loved one toward treatment, without confrontation, threats, or giving up.' },
      { type: 'p', text: 'The core principle of CRAFT is that families can learn to strategically reinforce sober behavior, allow natural consequences of using behavior, and work toward a planned, well-timed treatment request. A 2010 meta-analysis by Roozen and colleagues found CRAFT significantly outperformed both Al-Anon participation and the traditional Johnson Intervention model in getting resistant individuals to enter treatment.' },
      { type: 'p', text: 'CRAFT also addresses the family member\'s own wellbeing, which matters both intrinsically and because a depleted, dysregulated family member is simply less effective in this process. The approach is practical, skills-based, and can be learned through work with a trained clinician.' },
      { type: 'h2', text: 'When a Clinical Intervention Is the Right Move' },
      { type: 'p', text: 'Sometimes the situation has progressed to a point where a structured, professionally facilitated intervention is the most appropriate next step. This doesn\'t look like reality television. A clinically-led intervention is a carefully prepared conversation designed to move a resistant person toward accepting help.' },
      { type: 'p', text: 'The critical distinction is clinical oversight. An intervention involving someone in acute psychiatric distress, or someone with a trauma history, psychosis, or complex mental health presentation, requires a licensed clinician who can assess what\'s happening in real time and respond accordingly. A facilitator with certification but no clinical licensure is not equipped to manage a psychiatric emergency if one emerges in the room.' },
      { type: 'p', text: 'The right time to consider professional intervention is when family efforts have been exhausted, when safety is a genuine concern, or when the clinical complexity exceeds what the family can navigate alone.' },
      { type: 'h2', text: 'What You Can Do Right Now' },
      { type: 'p', text: 'If your loved one is refusing help, there are concrete steps that move the situation forward. Stop doing what isn\'t working, even when it feels caring. Get educated on where they are in the stages of change, because the right approach at the contemplation stage is different from the right approach at precontemplation. Consider working with a clinician yourself through CRAFT or family-focused therapy before your next conversation with your loved one. And have a plan ready. When someone says yes, even tentatively, the window is often short. Knowing exactly where you\'re sending them and being ready to move makes an enormous difference.' },
      { type: 'p', text: 'Refusal is not the end of the road. It\'s a clinical problem with evidence-based solutions. And it\'s one we navigate with families every day.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If your loved one is refusing treatment and you\'re not sure what to do next, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'Meyers, R.J. & Wolfe, B.L. (2004). Get Your Loved One Sober: Alternatives to Nagging, Pleading, and Threatening. Hazelden.',
      'Roozen, H.G., et al. (2010). A systematic review of the effectiveness of the community reinforcement approach in alcohol, cocaine and opioid addiction. Drug and Alcohol Dependence, 109(1-3), 9-19.',
      'Miller, W.R. & Rollnick, S. (2013). Motivational Interviewing: Helping People Change (3rd ed.). Guilford Press.',
      'Prochaska, J.O. & DiClemente, C.C. (1983). Stages and processes of self-change of smoking. Journal of Consulting and Clinical Psychology, 51(3), 390-395.',
      'Amador, X. (2001). I Am Not Sick, I Don\'t Need Help. Vida Press.',
    ],
  },

  {
    slug: 'first-episode-psychosis-guide-for-families',
    title: 'First Episode Psychosis: A Guide for Families',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'The moment a family realizes something is seriously wrong with how a loved one is thinking is one of the most frightening experiences they will face. First episode psychosis is treatable, but the window for early intervention matters more than most families realize.',
    metaDescription: 'First episode psychosis is treatable. Early intervention improves outcomes. A guide for families on warning signs, specialty care, and next steps.',
    date: '2026-03-02',
    category: 'Clinical Insights',
    image: null,
    relatedServices: ['mental-health', 'co-occurring-disorders', 'intervention-services'],
    body: [
      { type: 'p', text: 'The moment a family realizes something is seriously wrong with how a loved one is thinking, the strange beliefs, the voices, the terrifying disconnection from reality, is one of the most frightening experiences they will face. And one of the most disorienting.' },
      { type: 'p', text: 'Because nothing in the ordinary family toolkit prepares you for this. It doesn\'t look like depression. It doesn\'t look like anxiety. It often doesn\'t look like what people imagine mental illness looks like. And the mental health system\'s response, when you can access it, is often slower and less coordinated than the situation demands.' },
      { type: 'p', text: 'First episode psychosis is treatable. Outcomes can be genuinely good when the right care is accessed quickly. This guide is for families in the gap between what\'s happening and what to do about it.' },
      { type: 'h2', text: 'What First Episode Psychosis Actually Is' },
      { type: 'p', text: 'Psychosis is not a diagnosis. It\'s a symptom cluster. It describes a state in which a person\'s relationship to reality is significantly disrupted. This can include hallucinations (perceiving things that aren\'t there, most commonly auditory), delusions (fixed false beliefs that persist despite evidence to the contrary), disorganized thinking, and significant behavioral changes.' },
      { type: 'p', text: 'First episode psychosis (FEP) refers to the first time someone experiences these symptoms at a clinical threshold. It occurs most commonly in late adolescence and early adulthood, typically between ages 15 and 30, though it can emerge at any age. It may be associated with a primary psychotic disorder, a mood disorder, substance use, a medical condition, or significant psychological stress. The cause matters for treatment planning, but the urgency to act doesn\'t wait for the cause to be established.' },
      { type: 'h2', text: 'Warning Signs Families Often Miss' },
      { type: 'p', text: 'Psychosis rarely appears suddenly. Most cases are preceded by a prodromal period, a set of early warning signs that can precede full psychotic symptoms by months or even years. These include social withdrawal, declining school or work performance, sleep disruption, odd or magical thinking that doesn\'t rise to the level of delusion, increased suspiciousness, and a gradual loss of motivation or pleasure in previously enjoyed activities.' },
      { type: 'p', text: 'The prodrome is frequently attributed to depression, adolescent development, or stress, all reasonable interpretations in the moment. But in retrospect, most families say they knew something was wrong earlier than the crisis that finally brought them to treatment. Knowing the early warning signs means taking persistent functional decline seriously, particularly when it can\'t be explained by obvious stressors.' },
      { type: 'h2', text: 'Why Early Treatment Changes Outcomes' },
      { type: 'p', text: 'Duration of untreated psychosis (DUP), the time between symptom onset and treatment initiation, is one of the strongest predictors of long-term outcome. A meta-analysis by Correll and colleagues found that longer DUP is consistently associated with worse symptom outcomes, lower likelihood of full recovery, and greater functional impairment over time.' },
      { type: 'p', text: 'The practical implication is significant: every week of delay has measurable consequences. This is not a condition where "let\'s wait and see" is a neutral choice. Early treatment doesn\'t just reduce symptoms. It changes the neurological trajectory. The brain, particularly in adolescence and young adulthood, retains significant plasticity. Intervening early means intervening while that plasticity is greatest.' },
      { type: 'h2', text: 'Coordinated Specialty Care: The Gold Standard' },
      { type: 'p', text: 'The evidence-based standard for first episode psychosis is Coordinated Specialty Care (CSC), a multi-component team approach that integrates low-dose antipsychotic medication, individual and group psychotherapy, supported employment and education, family education and support, and clinical case management.' },
      { type: 'p', text: 'Cognitive Behavioral Therapy for psychosis (CBTp) is a core component of CSC. CBTp helps individuals examine the distressing beliefs and experiences associated with psychosis, changing the relationship to those experiences in ways that reduce distress and improve daily functioning, without necessarily eliminating the experiences entirely. The NIMH-funded RAISE study found that people receiving CSC showed significantly greater improvements in quality of life, symptoms, and work and school involvement than those receiving standard care.' },
      { type: 'h2', text: 'What Family Members Should and Shouldn\'t Do' },
      { type: 'p', text: 'Family involvement dramatically improves outcomes in first episode psychosis. Family psychoeducation, structured education for family members about the illness, its course, and evidence-based ways to respond, is a core component of every well-designed FEP program. Research consistently shows that high expressed emotion (criticism, hostility, over-involvement) in the family environment is associated with higher relapse rates. Learning how to modulate that, not through suppression but through understanding, is one of the most impactful things a family member can do.' },
      { type: 'p', text: 'What helps: staying calm during acute symptoms, maintaining routine and structure, staying engaged with the treatment team, and allowing the person to take appropriate steps toward independence as recovery progresses. What doesn\'t help: arguing with delusions, demanding insight before the person is clinically ready for it, or catastrophizing in front of the person experiencing symptoms.' },
      { type: 'h2', text: 'The Role of Clinical Case Management' },
      { type: 'p', text: 'First episode psychosis requires navigating multiple systems simultaneously: psychiatric evaluation, medication management, therapy, school or work accommodations, housing, and family coordination. These systems don\'t coordinate themselves. That coordination is precisely where clinical case management adds value.' },
      { type: 'p', text: 'For families trying to access CSC programs, which are not universally available and can have waitlists, a case manager who knows the landscape and can advocate for priority access is often the difference between getting into the right program and waiting months. If you\'re trying to navigate this alone, you shouldn\'t have to be.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If your family is navigating a first psychotic episode, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'Kane, J.M., et al. (2016). Comprehensive versus usual community care for first-episode psychosis: 2-year outcomes from the NIMH RAISE early treatment program. American Journal of Psychiatry, 173(4), 362-372.',
      'Correll, C.U., et al. (2018). Efficacy of 42 pharmacologic cotreatment strategies added to antipsychotic monotherapy in schizophrenia. JAMA Psychiatry, 74(7), 675-684.',
      'McGorry, P.D. (2015). Early intervention in psychosis: obvious, effective, overdue. Journal of Nervous and Mental Disease, 203(5), 310-318.',
      'Dixon, L.B., et al. (2016). Implementing coordinated specialty care for first episode psychosis. Psychiatric Services, 67(7), 704-706.',
      'Onwumere, J., et al. (2011). Family intervention in psychosis: a review of single-family approaches. Advances in Psychiatric Treatment, 17(2), 94-103.',
    ],
  },

  {
    slug: 'what-is-a-clinical-intervention',
    title: 'What Is a Clinical Intervention? (And How It Differs From What You See on TV)',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'When most people hear "intervention," they picture a surprise confrontation from a reality TV show. That model exists. It can also cause significant harm when applied without clinical judgment. Here\'s what a professionally facilitated, clinically-led intervention actually looks like.',
    metaDescription: 'A clinical intervention is not an ambush. What evidence-based models look like, why clinical oversight matters, and when intervention is the right step.',
    date: '2026-03-02',
    category: 'Clinical Insights',
    image: null,
    relatedServices: ['intervention-services', 'substance-use', 'mental-health'],
    body: [
      { type: 'p', text: 'When most people hear the word "intervention," they picture a scene from reality television: a surprise confrontation in a living room, tears, ultimatums, and someone being escorted onto a plane. That model exists. It can also cause significant harm when applied without clinical judgment.' },
      { type: 'p', text: 'In reality, intervention is a clinical process, one that looks very different depending on the model used, the individual involved, and the professional facilitating it. Understanding those differences matters, because not every approach is appropriate for every situation.' },
      { type: 'h2', text: 'What an Intervention Is, and Isn\'t' },
      { type: 'p', text: 'At its core, an intervention is a structured, guided process designed to help someone recognize the impact of their behavior and move toward accepting help. It\'s not a punishment, a trap, or an ambush. It\'s a conversation, one that, when done well, is prepared far in advance, involves the people who matter most to the person, and is facilitated by someone trained to manage what emerges.' },
      { type: 'p', text: 'The goal is not to force someone into treatment. Forced treatment without internal motivation has poor long-term outcomes. The goal is to shift the balance of a person\'s ambivalence toward change, to make the case for help in a way that is honest, compassionate, and hard to dismiss.' },
      { type: 'h2', text: 'The Johnson Model: What Most People Picture' },
      { type: 'p', text: 'The Johnson Intervention, developed by Vernon Johnson in the 1960s, is the confrontational model that most people recognize. It involves a surprise gathering of loved ones who each read prepared statements about how the person\'s behavior has affected them, followed by a direct request to enter treatment, often with an ultimatum if refused.' },
      { type: 'p', text: 'The Johnson model can work. It has also been criticized in the clinical literature for its confrontational nature, which can increase shame, increase resistance, and in complex cases, particularly those involving trauma or psychiatric instability, can escalate in ways that require clinical management. Research by White and Miller found that confrontational approaches produced outcomes no better than, and sometimes worse than, non-confrontational alternatives.' },
      { type: 'h2', text: 'The ARISE Model: A Gentler, Evidence-Informed Approach' },
      { type: 'p', text: 'The ARISE (A Relational Intervention Sequence for Engagement) model, developed by Judith Landau and James Garrett, takes a different approach. Rather than a surprise confrontation, ARISE involves a series of progressively structured conversations, beginning with the person\'s concerned network (family, close friends, colleagues) and ideally including the person themselves from the first call.' },
      { type: 'p', text: 'The philosophy behind ARISE is that people are more likely to accept help when they feel invited into a process rather than ambushed by one. ARISE leans heavily on principles drawn from Motivational Interviewing: meeting the person where they are, reinforcing their own stated reasons for change, and reducing the defensiveness that confrontation often triggers. The research on ARISE shows high rates of treatment engagement with significantly lower emotional fallout for families.' },
      { type: 'h2', text: 'Why Clinical Oversight Changes Everything' },
      { type: 'p', text: 'Here is what I want every family to understand: an intervention facilitated by a certified interventionist who holds no clinical licensure is a fundamentally different product than one facilitated by a licensed clinician.' },
      { type: 'p', text: 'Interventions can surface things no one anticipated. Acute psychiatric symptoms. Trauma responses. Suicidal ideation. Psychotic features that have been masked by substance use. A certified interventionist, regardless of how skilled or well-meaning, is not trained to clinically assess or manage these presentations. A licensed clinician is. When something complex emerges in the room, having someone who can accurately assess what\'s happening and respond with clinical judgment isn\'t a luxury. It\'s the difference between a situation that helps and one that harms.' },
      { type: 'h2', text: 'When Intervention Is, and Isn\'t, the Right Step' },
      { type: 'p', text: 'Intervention is most appropriate when: the person has a significant pattern of use or untreated mental illness with clear functional consequences, family efforts have been exhausted, there is a support system willing to participate, and safety permits a structured process.' },
      { type: 'p', text: 'Intervention is not appropriate when: the person is in acute psychiatric crisis, there is active domestic violence in the relationship system, there is a high risk of self-harm with no safety plan in place, or the family system is too fragmented to participate meaningfully. A skilled clinician helps families assess which situation they\'re in before committing to a course of action.' },
      { type: 'h2', text: 'What Our Interventions Look Like' },
      { type: 'p', text: 'Every intervention we facilitate begins with a thorough assessment of the individual, the family system, the clinical history, and the current safety picture. We work with the family for days or weeks before any conversation with the identified person, preparing them for what to say, how to say it, and how to respond to resistance. When the moment comes, we are in the room as licensed clinicians who can read what\'s happening and adjust in real time.' },
      { type: 'p', text: 'We don\'t just get someone to say yes. We make sure there\'s somewhere good to say yes to, with a bed, a clinical match, and a plan already in place before the conversation happens.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If you\'re considering an intervention and want to understand your options, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'Johnson, V.E. (1986). Intervention: How to Help Someone Who Doesn\'t Want Help. Johnson Institute.',
      'Landau, J. & Garrett, J. (2006). Invitational intervention: a step-by-step guide for clinicians helping families engage resistant substance abusers in treatment. Alcoholism Treatment Quarterly, 24(1-2), 89-109.',
      'White, W. & Miller, W. (2007). The use of confrontation in addiction treatment: history, science, and time for change. Counselor, 8(4), 12-30.',
      'Roozen, H.G., et al. (2010). A systematic review of the effectiveness of the community reinforcement approach. Drug and Alcohol Dependence, 109(1-3), 9-19.',
      'Miller, W.R. & Rollnick, S. (2013). Motivational Interviewing: Helping People Change (3rd ed.). Guilford Press.',
    ],
  },

  {
    slug: 'co-occurring-disorders-when-addiction-and-mental-illness-collide',
    title: 'Co-Occurring Disorders: When Addiction and Mental Illness Show Up Together',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'The most common mistake in treating addiction is treating it alone. Nearly half of people with a substance use disorder also have a co-occurring mental health condition. When one goes untreated, the other almost always follows.',
    metaDescription: 'Addiction alongside mental illness requires integrated treatment. Why sequential treatment fails and what evidence-based integrated care looks like.',
    date: '2026-03-02',
    category: 'Clinical Insights',
    image: null,
    relatedServices: ['co-occurring-disorders', 'mental-health', 'substance-use'],
    body: [
      { type: 'p', text: 'The most common mistake in treating addiction is treating it alone.' },
      { type: 'p', text: 'According to the Substance Abuse and Mental Health Services Administration, approximately 9.2 million adults in the United States have both a mental health disorder and a substance use disorder, what clinicians call co-occurring disorders, or dual diagnosis. Yet the majority of treatment programs are still designed to treat one or the other, not both simultaneously.' },
      { type: 'p', text: 'The consequences of that gap are significant. When a mental health condition drives substance use and goes untreated, relapse is almost inevitable. When substance use masks or worsens a psychiatric condition and the psychiatric component goes unaddressed, recovery stalls. The two conditions feed each other in ways that require both to be treated at once.' },
      { type: 'h2', text: 'Why Co-Occurring Disorders Are So Frequently Missed' },
      { type: 'p', text: 'There are several reasons co-occurring disorders are underdiagnosed. First, many psychiatric symptoms are temporarily masked by active substance use, or temporarily worsened by it, making accurate assessment difficult until there is a period of sobriety. A person who presents with severe depression during active alcohol use may have a primary depressive disorder, alcohol-induced depressive disorder, or both. You often can\'t tell until they\'ve been sober for several weeks.' },
      { type: 'p', text: 'Second, the treatment system itself has historically been fragmented along these lines, with substance use treatment programs and mental health programs operating separately, with different funding streams, different regulatory environments, and different clinical cultures. Patients fell into the gap between systems: too mentally ill for most addiction programs, too addicted for most mental health programs.' },
      { type: 'p', text: 'Third, the stigma associated with both conditions compounds reluctance to disclose fully, making complete clinical pictures harder to obtain.' },
      { type: 'h2', text: 'The Self-Medication Hypothesis: Real, But Incomplete' },
      { type: 'p', text: 'One of the most common frameworks families use to understand co-occurring disorders is the self-medication hypothesis, the idea that their loved one uses substances to manage the symptoms of an underlying mental health condition. There is real research supporting this: people with PTSD, bipolar disorder, anxiety disorders, and schizophrenia all show elevated rates of substance use, and the neurological rationale for why is well-established.' },
      { type: 'p', text: 'But the relationship is bidirectional. Substance use also causes, worsens, and sustains psychiatric symptoms. Heavy alcohol use causes depression. Stimulant use causes anxiety and, in some cases, psychosis. Cannabis use is now clearly linked to elevated psychosis risk. The self-medication framing, while useful for building empathy, can inadvertently suggest that treating the mental health condition will resolve the substance use problem. That is often not the case.' },
      { type: 'h2', text: 'Why Sequential Treatment Fails' },
      { type: 'p', text: 'For years, the standard approach was sequential treatment: address the substance use first, then address the mental health condition, or vice versa. The logic made intuitive sense. The outcomes didn\'t support it. Research consistently shows that treating co-occurring disorders sequentially produces worse outcomes than integrated treatment, in which both conditions are addressed simultaneously by a coordinated team.' },
      { type: 'p', text: 'Integrated Dual Diagnosis Treatment (IDDT), developed through the Dartmouth Psychiatric Research Center and extensively studied by Robert Drake and colleagues, is the evidence-based standard for this population. IDDT combines motivational interviewing, cognitive behavioral therapy, pharmacotherapy when appropriate, family education, and supported employment into a single, coordinated care framework. The research on IDDT demonstrates significantly better outcomes on substance use, psychiatric symptoms, and functional recovery compared to parallel or sequential approaches.' },
      { type: 'h2', text: 'DBT and ACT: Evidence-Based Therapies That Serve This Population Well' },
      { type: 'p', text: 'Dialectical Behavior Therapy (DBT), originally developed by Marsha Linehan for borderline personality disorder, has become one of the most widely used and well-researched treatments for co-occurring disorders. DBT\'s emphasis on distress tolerance, emotional regulation, mindfulness, and interpersonal effectiveness addresses many of the underlying vulnerabilities that drive both psychiatric symptoms and substance use. Linehan\'s own research on DBT adapted for substance use disorders showed significant reductions in both drug use and suicidal behavior.' },
      { type: 'p', text: 'Acceptance and Commitment Therapy (ACT) offers a complementary framework, helping individuals develop psychological flexibility, observe their thoughts and feelings without being controlled by them, and commit to value-driven action even in the presence of distress. For people who have spent years using substances to escape internal experience, ACT\'s approach to building tolerance for difficult emotions is particularly relevant.' },
      { type: 'h2', text: 'What to Look for in Dual Diagnosis Treatment' },
      { type: 'p', text: 'Not every program that calls itself "dual diagnosis capable" actually provides integrated treatment. When evaluating programs for someone with co-occurring disorders, the right questions to ask include: Does the program have psychiatric staff on-site, or only on consultation? Is the substance use treatment and mental health treatment delivered by the same team or by separate providers in separate tracks? Does the program have experience with the specific psychiatric presentation involved, including trauma, psychosis, bipolar disorder, or severe depression? Is medication management integrated into the treatment plan from day one?' },
      { type: 'p', text: 'These distinctions are the difference between a program that can hold this complexity and one that will discharge a person the first time psychiatric symptoms complicate the expected course. That\'s the work of treatment placement: not just finding a bed, but finding the right clinical environment for the actual presentation.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If you\'re concerned a loved one may have co-occurring disorders, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'SAMHSA (2020). Co-occurring disorders and other health conditions. National Survey on Drug Use and Health.',
      'Drake, R.E., et al. (2001). Implementing dual diagnosis services for clients with severe mental illness. Psychiatric Services, 52(4), 469-476.',
      'Linehan, M.M., et al. (2002). Dialectical behavior therapy versus comprehensive validation therapy plus 12-step for the treatment of opioid dependent women meeting criteria for borderline personality disorder. Drug and Alcohol Dependence, 67(1), 13-26.',
      'Hayes, S.C., et al. (2012). Acceptance and Commitment Therapy: The Process and Practice of Mindful Change (2nd ed.). Guilford Press.',
      'Kessler, R.C. (2004). The epidemiology of dual diagnosis. Biological Psychiatry, 56(10), 730-737.',
    ],
  },

  {
    slug: 'how-to-choose-a-treatment-program',
    title: 'How to Choose a Treatment Program: What to Ask, What to Avoid',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'There are over 15,000 substance use treatment programs in the United States. They are not equal. Knowing how to evaluate them, and what to avoid, is one of the most important decisions a family will make.',
    metaDescription: 'Choosing the right treatment program is complex. What questions to ask, red flags to watch for, and how case management helps find the right fit.',
    date: '2026-03-02',
    category: 'Family Guidance',
    image: null,
    relatedServices: ['treatment-placement', 'substance-use', 'co-occurring-disorders'],
    body: [
      { type: 'p', text: 'There are over 15,000 substance use treatment programs in the United States. They are not equal.' },
      { type: 'p', text: 'Some are excellent. Some are well-intentioned but clinically limited. Some are exploitative, designed to capture insurance revenue rather than deliver care. And without insider knowledge, they can be extremely difficult to tell apart from the outside. A beautiful facility and a compelling website don\'t tell you anything meaningful about clinical quality.' },
      { type: 'p', text: 'This guide is designed to help families and individuals make a genuinely informed decision. Not just find "a program," but find the right program for a specific person with a specific set of needs.' },
      { type: 'h2', text: 'Understanding Levels of Care' },
      { type: 'p', text: 'Treatment is not a single thing. The American Society of Addiction Medicine (ASAM) has developed a widely used framework that defines levels of care on a continuum from outpatient to medically managed intensive inpatient. The right level of care for any individual depends on the severity of the substance use, the presence of co-occurring medical or psychiatric conditions, the stability of the living environment, and the degree of support available outside of treatment.' },
      { type: 'p', text: 'Placing someone at a level of care that doesn\'t match their clinical need, either too high or too low, produces poor outcomes. Someone with a severe opioid use disorder and active suicidal ideation does not belong in an outpatient program. Someone with a mild alcohol use disorder and a stable home environment does not necessarily need residential treatment. Matching level of care to clinical need is a clinical determination, not a sales decision.' },
      { type: 'h2', text: 'Questions Every Family Should Ask' },
      { type: 'p', text: 'Before placing a loved one in any program, these are the questions that actually matter: What is the staff-to-client ratio? What are the credentials of the clinical team? Are therapists licensed? Is there a psychiatrist on staff, or only available by consultation? What evidence-based treatment modalities are used? The answer should include specific approaches: Cognitive Behavioral Therapy, Motivational Interviewing, Medication-Assisted Treatment (MAT) where clinically indicated, Contingency Management. "We use a 12-step model" is not a complete clinical answer.' },
      { type: 'p', text: 'Also ask: What is the program\'s approach to co-occurring mental health conditions? What happens if a psychiatric crisis emerges during treatment? Is there capacity to manage it, or will the person be discharged? What does the discharge and aftercare planning process look like? A program that cannot clearly answer these questions is a program that hasn\'t thought carefully enough about what happens when treatment gets complicated.' },
      { type: 'h2', text: 'Red Flags to Watch For' },
      { type: 'p', text: 'The behavioral health industry has a documented patient brokering problem, arrangements where individuals are paid to refer clients to specific facilities regardless of clinical fit. This practice is illegal in many states and is widespread enough that families should be cautious about any referral source that seems primarily interested in getting someone placed quickly rather than evaluating clinical need.' },
      { type: 'p', text: 'Other red flags include: guarantees of success (no ethical program offers these), pressure to admit immediately without an assessment, inability or unwillingness to provide information about clinical credentials, programs that do not accept insurance and cannot clearly explain why, and programs that discourage contact with family during early treatment without clear clinical justification.' },
      { type: 'h2', text: 'What Evidence-Based Treatment Actually Looks Like' },
      { type: 'p', text: 'The National Institute on Drug Abuse (NIDA) has published well-supported principles of effective treatment that provide a useful benchmark. Effective treatment addresses the whole person, not just drug use, but co-occurring medical, psychological, social, and vocational needs. It uses medications when appropriate (MAT for opioid and alcohol use disorders has the strongest evidence base of any addiction intervention). It is long enough, because research consistently shows that outcomes improve with longer duration, and that programs shorter than 90 days are often insufficient for severe presentations.' },
      { type: 'p', text: 'Cognitive Behavioral Therapy (CBT) is one of the most extensively researched therapeutic approaches in addiction treatment. CBT helps individuals identify and modify the thoughts, emotions, and situations that trigger use, and develop concrete coping skills that substitute for substance use. Motivational Interviewing, used throughout treatment rather than only at intake, continues to strengthen intrinsic motivation as treatment progresses.' },
      { type: 'h2', text: 'Why Treatment Placement Is Its Own Specialty' },
      { type: 'p', text: 'The best treatment program for your loved one is not necessarily the most expensive, the most well-known, or the closest. It\'s the one whose clinical capabilities match what this specific person actually needs: their diagnostic picture, their trauma history, their co-occurring conditions, their family situation, their financial realities.' },
      { type: 'p', text: 'We have personally evaluated hundreds of programs across the country. We know which ones genuinely deliver on their dual diagnosis claims, which ones have strong trauma-informed care, which ones are the right fit for young adults versus older adults, and which ones look good on paper but fall short in practice. That knowledge is what treatment placement actually means, not a referral to a list, but a match built on clinical judgment.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If you\'re trying to find the right treatment program, ', linkText: 'contact us. We can help you evaluate your options', href: '/contact', suffix: '.' },
    ],
    references: [
      'ASAM (2023). The ASAM Criteria: Treatment Criteria for Addictive, Substance-Related, and Co-Occurring Conditions (4th ed.). American Society of Addiction Medicine.',
      'NIDA (2018). Principles of Drug Addiction Treatment: A Research-Based Guide (3rd ed.). National Institute on Drug Abuse.',
      'Kelly, J.F. & White, W.L. (2011). Addiction Recovery Management: Theory, Research and Practice. Humana Press.',
      'Magill, M. & Ray, L.A. (2009). Cognitive-behavioral treatment with adult alcohol and illicit drug users. Journal of Studies on Alcohol and Drugs, 70(4), 516-527.',
      'Substance Abuse and Mental Health Services Administration (2019). Key substance use and mental health indicators in the United States. National Survey on Drug Use and Health.',
    ],
  },

  {
    slug: 'what-does-a-clinical-case-manager-do',
    title: 'What Does a Clinical Case Manager Actually Do?',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'People hire us after they\'ve tried everything else. After the emergency room visits, the failed treatment attempts, the therapists who didn\'t specialize in what was needed. By the time someone calls, they\'re usually exhausted. Here\'s what a clinical case manager actually does, and why it matters.',
    metaDescription: 'What does a clinical case manager actually do? Who benefits most, and how it differs from therapy or standard care coordination.',
    date: '2026-03-02',
    category: 'Clinical Insights',
    image: null,
    relatedServices: ['substance-use', 'mental-health', 'co-occurring-disorders'],
    body: [
      { type: 'p', text: 'People hire us after they\'ve tried everything else. After the emergency room visits, the failed treatment attempts, the therapists who didn\'t specialize in what was needed, the insurance denials, the waiting lists. By the time someone calls Holistic Solutions, they\'re usually exhausted by the situation and by the system.' },
      { type: 'p', text: 'Clinical case management exists to solve a specific and common problem: the gap between a person who needs complex, coordinated care and a healthcare system that wasn\'t designed to deliver it. Understanding what a case manager actually does, and doesn\'t do, helps clarify when it\'s the right resource.' },
      { type: 'h2', text: 'The Core Functions' },
      { type: 'p', text: 'Clinical case management has four primary functions, defined by the Case Management Society of America (CMSA): assessment, planning, implementation, and monitoring. In practice, these functions look like this: understanding who a person is and what they need across every relevant domain, clinical, social, environmental, vocational, familial. Building a care plan that addresses that full picture. Coordinating the providers, programs, and services that deliver it. And staying actively engaged over time to monitor progress, address problems, and adjust the plan as circumstances change.' },
      { type: 'p', text: 'What distinguishes clinical case management from general care coordination is the clinical lens. A case manager with a clinical background, licensed in social work, counseling, or marriage and family therapy, brings the capacity to assess psychiatric symptoms, understand diagnostic complexity, evaluate the appropriateness of different levels of care, and advocate with clinical authority within systems that respond to clinical language.' },
      { type: 'h2', text: 'Assessment: Where Everything Starts' },
      { type: 'p', text: 'A thorough biopsychosocial assessment is the foundation of good case management. This means understanding not just a person\'s diagnosis, but their psychiatric and medical history, their substance use history, their trauma history, their family system, their living situation, their financial resources, their vocational status, their strengths, and their goals. It means understanding the whole person, not just the presenting problem.' },
      { type: 'p', text: 'The assessment shapes everything that follows. A case manager who skips or shortchanges the assessment is building a plan on an incomplete foundation. The clinical literature on person-centered case management, developed by Charles Rapp and Richard Goscha, emphasizes beginning from a person\'s strengths and stated goals rather than deficits and diagnoses, an orientation that produces better engagement and better outcomes.' },
      { type: 'h2', text: 'Coordination: The Work Between Appointments' },
      { type: 'p', text: 'Most of the work of case management happens in the space between clinical appointments: the phone calls to insurance companies, the conversations between a therapist and a prescriber who have never communicated, the coordination between a treatment program and a family, the follow-up after a discharge that had no aftercare plan.' },
      { type: 'p', text: 'This coordination sounds administrative. It isn\'t. It requires clinical judgment at every step: knowing when a situation has changed enough to warrant a higher level of care, recognizing when a provider\'s approach isn\'t matching the clinical need, identifying when a family dynamic is undermining treatment progress and knowing how to address it. The navigation of complex systems requires clinical fluency with those systems.' },
      { type: 'h2', text: 'Advocacy: The Role Most People Don\'t Know They Need' },
      { type: 'p', text: 'One of the most underappreciated functions of a clinical case manager is advocacy, representing a client\'s clinical needs within systems that often prioritize cost, administrative convenience, or standard protocol over individual circumstances.' },
      { type: 'p', text: 'Insurance appeals. Prior authorization battles. Discharge planning disputes. Placement decisions that don\'t match the clinical picture. In each of these situations, having someone who can make the clinical case in language the system understands, and who knows what recourse is available when the initial response is no, produces meaningfully different outcomes. It\'s the difference between navigating these systems alone and having someone in your corner who\'s done it hundreds of times.' },
      { type: 'h2', text: 'Who Benefits Most from Case Management' },
      { type: 'p', text: 'Case management produces the most value in situations involving complexity: multiple co-occurring conditions, repeated treatment attempts without lasting success, a fragmented care team, significant family involvement that needs coordination, high-stakes decisions about level of care, or a transition period where continuity is critical.' },
      { type: 'p', text: 'It\'s not a substitute for therapy, psychiatry, or primary care. It\'s the connective tissue between them, the function that ensures a person\'s various providers are actually working in concert, and that the person themselves stays engaged, supported, and on track through what is often a long and nonlinear process.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'To learn more about whether clinical case management is right for your situation, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'Case Management Society of America (2022). CMSA Standards of Practice for Case Management. CMSA.',
      'Rapp, C.A. & Goscha, R.J. (2006). The Strengths Model: Case Management with People with Psychiatric Disabilities (2nd ed.). Oxford University Press.',
      'Stanhope, V. & Henwood, B.F. (2014). Activating people to address their health care needs: learning from recovery. Community Mental Health Journal, 50(7), 777-783.',
      'Mueser, K.T., et al. (1998). Assertive community treatment and social skills training for the treatment of schizophrenia. Journal of Consulting and Clinical Psychology, 66(1), 58-73.',
      'Katon, W.J. (2012). Collaborative care for patients with depression and chronic illnesses. New England Journal of Medicine, 366(11), 1064-1065.',
    ],
  },

  {
    slug: 'case-manager-vs-therapist-whats-the-difference',
    title: 'Case Manager vs. Therapist: What\'s the Difference and When Do You Need Each?',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: '"We already have a therapist. Why would we need a case manager too?" It\'s the most common question I hear on initial calls. The answer matters, because therapy and case management serve fundamentally different functions.',
    metaDescription: 'A therapist and a case manager serve different functions. Key differences, when you need one vs. the other, and when having both is required.',
    date: '2026-03-02',
    category: 'Clinical Insights',
    image: null,
    relatedServices: ['mental-health', 'substance-use', 'co-occurring-disorders'],
    body: [
      { type: 'p', text: '"We already have a therapist. Why would we need a case manager too?"' },
      { type: 'p', text: 'It\'s the most common question I hear on initial calls, and it\'s a fair one. Both roles involve licensed clinical professionals. Both involve helping someone navigate mental health or substance use challenges. But they serve fundamentally different functions, and understanding the difference helps families figure out what their situation actually requires.' },
      { type: 'h2', text: 'What Therapy Does' },
      { type: 'p', text: 'Therapy is a structured clinical relationship in which a licensed provider works with a client on psychological growth, symptom reduction, insight, emotional processing, and behavioral change. It happens in a session, typically 45 to 50 minutes, typically weekly, and the work is primarily relational and intrapsychic.' },
      { type: 'p', text: 'Good therapy changes people. Evidence-based modalities like Cognitive Behavioral Therapy (CBT), Dialectical Behavior Therapy (DBT), EMDR for trauma, and Acceptance and Commitment Therapy (ACT) have robust research supporting their effectiveness for a wide range of conditions. A skilled therapist working within their area of competence is an extraordinarily valuable resource.' },
      { type: 'p', text: 'What therapy is not designed to do: coordinate care across multiple providers, navigate insurance and system-level obstacles, make treatment placement decisions, accompany someone to appointments, or provide the kind of between-session support and environmental management that complex cases often require. A therapist who is spending session time coordinating with an insurance company or calling a treatment program is a therapist whose session time is being misused.' },
      { type: 'h2', text: 'What Case Management Does' },
      { type: 'p', text: 'Case management focuses on coordination, navigation, advocacy, and logistics. It lives largely outside of formal clinical sessions, in the systems and environments that either support or undermine a person\'s recovery and wellbeing.' },
      { type: 'p', text: 'A clinical case manager conducts a comprehensive biopsychosocial assessment, builds and monitors a care plan, coordinates among the person\'s various providers, navigates insurance and placement decisions, addresses practical barriers to treatment engagement, and provides continuity through transitions that are otherwise high-risk. The case manager ensures that all the components of a person\'s care are actually working together, and that when something shifts, someone with clinical judgment is paying attention.' },
      { type: 'h2', text: 'A Simple Way to Think About the Difference' },
      { type: 'p', text: 'Therapy works on the inside. Case management works on the outside. Therapy helps someone process their experience, develop new ways of thinking and relating, and build internal resources for managing their condition. Case management ensures the external environment, providers, programs, systems, supports, is actually set up to make that internal work possible.' },
      { type: 'p', text: 'For many people with straightforward presentations, therapy alone is sufficient. For people with complex, multi-system needs, co-occurring disorders, repeated treatment failures, fragmented care, acute psychiatric instability, high-stakes transitions, the external environment is often as much of the problem as the internal one. Case management addresses what therapy can\'t reach.' },
      { type: 'h2', text: 'When You Need Both' },
      { type: 'p', text: 'The highest-functioning treatment configurations for complex presentations integrate both. Therapy provides the ongoing relational and clinical container. Case management provides the coordination that makes everything else work. The two roles complement each other when they\'re communicating well, and a good case manager will actively work to support the therapeutic relationship, not compete with it.' },
      { type: 'p', text: 'In collaborative care models, which have strong research support in the treatment of depression, anxiety, and co-occurring disorders, the combination of therapy, pharmacotherapy, and care coordination produces significantly better outcomes than any single intervention alone. The case manager in these models is not adding redundancy. They\'re adding a function that genuinely doesn\'t exist anywhere else in the care system.' },
      { type: 'h2', text: 'When Case Management Comes First' },
      { type: 'p', text: 'There are situations where starting with case management before therapy is the right call. When someone is in acute crisis and the immediate need is stabilization and placement, not clinical processing. When someone has been through multiple failed treatment attempts and needs an honest assessment of what\'s been missing before trying again. When the logistical and systemic obstacles to treatment engagement are so significant that they need to be addressed before any therapeutic relationship can take hold.' },
      { type: 'p', text: 'Therapy requires stability. Case management can help build the stability that therapy requires.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'Not sure whether you need a therapist, a case manager, or both? ', linkText: 'Contact us and we\'ll help you figure it out', href: '/contact', suffix: '.' },
    ],
    references: [
      'Case Management Society of America (2022). CMSA Standards of Practice for Case Management.',
      'Katon, W.J. (2012). Collaborative care for patients with depression and chronic illnesses. New England Journal of Medicine, 366(11), 1064-1065.',
      'Hofmann, S.G., et al. (2012). The efficacy of cognitive behavioral therapy: a review of meta-analyses. Cognitive Therapy and Research, 36(5), 427-440.',
      'Linehan, M.M. (1993). Cognitive-Behavioral Treatment of Borderline Personality Disorder. Guilford Press.',
      'Hayes, S.C., et al. (2012). Acceptance and Commitment Therapy (2nd ed.). Guilford Press.',
    ],
  },

  {
    slug: 'what-happens-after-treatment',
    title: 'What Happens After Treatment: The Transition Period Most Families Aren\'t Prepared For',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'The most dangerous moment in someone\'s recovery is often the day they leave treatment. The transition back to daily life, without the structure, support, and clinical oversight of a residential program, is where relapse most commonly occurs. Here\'s what that period actually requires.',
    metaDescription: 'The transition from treatment to daily life is the highest-risk period. Evidence-based continuing care, aftercare planning, and how families can help.',
    date: '2026-03-02',
    category: 'Family Guidance',
    image: null,
    relatedServices: ['recovery-coaching', 'substance-use', 'mental-health'],
    body: [
      { type: 'p', text: 'The most dangerous moment in someone\'s recovery is often the day they leave treatment.' },
      { type: 'p', text: 'This isn\'t an exaggeration. The research on post-treatment relapse is sobering. Studies consistently show that relapse rates are highest in the first weeks and months after leaving a residential or intensive program, when the structure, peer support, and clinical oversight that made treatment work are suddenly absent, and the person is back in the environment where the problem began.' },
      { type: 'p', text: 'Most families are not prepared for this. They\'ve done the hard work of getting their loved one into treatment. They\'ve watched them improve. They expect the recovery to continue. What they don\'t always understand is that treatment is the beginning of recovery, not the end of it.' },
      { type: 'h2', text: 'Why the Transition Period Is So High-Risk' },
      { type: 'p', text: 'Residential treatment provides a highly controlled environment: no access to substances, around-the-clock clinical support, peer community, structured daily schedules, and physical separation from triggering people, places, and situations. When someone leaves that environment, all of those protective factors disappear simultaneously.' },
      { type: 'p', text: 'The neurological reality compounds this. Addiction involves changes to the brain\'s reward system, stress response, and prefrontal cortical function, the part of the brain responsible for impulse control, decision-making, and resisting urges. Those changes don\'t resolve in 30 or 60 days. Recovery is a process of gradual neurological and behavioral change that unfolds over months and years, not weeks. A discharge plan that doesn\'t account for this reality is a plan that sets people up to fail.' },
      { type: 'h2', text: 'What the Research Says About Continuing Care' },
      { type: 'p', text: 'The evidence on continuing care, the clinical term for ongoing treatment and support after an initial episode of care, is clear and consistent. A landmark meta-analysis by James McKay found that active continuing care interventions, particularly those that are proactive and adaptive, significantly improve long-term outcomes compared to standard aftercare. The benefit is strongest for people with more severe presentations and those with co-occurring psychiatric conditions.' },
      { type: 'p', text: 'Continuing care doesn\'t need to be intensive to be effective. What matters more than intensity is consistency and duration. Sustained, lower-intensity support over 12 months produces better outcomes than a brief intensive intervention that ends at discharge. Recovery management, the idea that addiction is a chronic condition that requires ongoing monitoring and support rather than a single acute episode of treatment, is the emerging paradigm in the field.' },
      { type: 'h2', text: 'Relapse Is Not Failure. But It Is Information.' },
      { type: 'p', text: 'One of the most important things families can understand is that relapse, while painful and potentially dangerous, is not a sign that treatment failed or that recovery is impossible. Relapse rates for substance use disorders are comparable to those for other chronic conditions like diabetes and hypertension, conditions no one would describe as untreatable.' },
      { type: 'p', text: 'The cognitive-behavioral model of relapse prevention, developed by G. Alan Marlatt and Judith Gordon, conceptualizes relapse as a process rather than an event, one that begins with high-risk situations, moves through a lapse, and may or may not progress to full relapse depending on how the person responds to the initial slip. CBT-based relapse prevention helps people identify their high-risk situations, develop specific coping plans, and change the cognitive response to a lapse so it doesn\'t become a reason to give up entirely.' },
      { type: 'h2', text: 'What a Strong Aftercare Plan Actually Includes' },
      { type: 'p', text: 'An aftercare plan is not a list of phone numbers and a recommendation to attend meetings. A genuinely protective continuing care plan includes: a step-down level of care when clinically indicated (from residential to PHP to IOP to outpatient), ongoing individual therapy with a provider who specializes in the relevant condition, medication management when appropriate, peer support, a stable and sober living environment, meaningful structure and purpose (work, school, or structured programming), and a system for regular check-ins with someone who has clinical oversight.' },
      { type: 'p', text: 'It also needs to account for the family system. The patterns that existed before treatment don\'t automatically change because the person in treatment has changed. Family therapy or family education during the transition period is often one of the highest-leverage investments a family can make.' },
      { type: 'h2', text: 'The Role of Recovery Coaching' },
      { type: 'p', text: 'Recovery coaches, sometimes called sober coaches or recovery support specialists, provide between-appointment, real-world support during the transition period. A good recovery coach accompanies a person to appointments, helps build daily structure, provides accountability, and serves as a point of contact when situations that could lead to relapse begin to develop.' },
      { type: 'p', text: 'When recovery coaching is layered with clinical case management, the two roles create a remarkably effective continuing care structure: the case manager maintains clinical oversight and adjusts the care plan as needed, while the recovery coach provides the on-the-ground, daily support that holds the plan together. This combination is particularly effective for people in the first year of recovery, when the risk is highest and the need for support is greatest.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If a loved one is leaving treatment soon and you\'re not sure what comes next, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'McKay, J.R. (2009). Treating substance use disorders with adaptive continuing care. American Psychological Association.',
      'Marlatt, G.A. & Gordon, J.R. (1985). Relapse Prevention: Maintenance Strategies in the Treatment of Addictive Behaviors. Guilford Press.',
      'Dennis, M.L., et al. (2007). The SAMHSA continuing care guidance. Substance Abuse and Mental Health Services Administration.',
      'White, W.L. (2008). Recovery management and recovery-oriented systems of care: scientific rationale and promising practices. Northeast Addiction Technology Transfer Center.',
      'McLellan, A.T., et al. (2000). Drug dependence, a chronic medical illness. JAMA, 284(13), 1689-1695.',
    ],
  },

  {
    slug: 'how-to-help-someone-with-a-dual-diagnosis',
    title: 'How to Help Someone You Love Who Has a Dual Diagnosis',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'If you have a loved one with both a mental health condition and a substance use problem, you already know that nothing about it is simple. The advice that works for "just" addiction doesn\'t always apply. Here\'s what does.',
    metaDescription: 'Helping a loved one with dual diagnosis requires a different approach. What it means, why integrated treatment matters, and how families can help.',
    date: '2026-03-02',
    category: 'Family Guidance',
    image: null,
    relatedServices: ['co-occurring-disorders', 'mental-health', 'substance-use'],
    body: [
      { type: 'p', text: 'If you have a loved one with both a mental health condition and a substance use problem, you already know that nothing about it is simple. The advice that works for "just" addiction doesn\'t always apply. The advice that works for "just" mental illness doesn\'t always apply. And most of the time, the treatment system isn\'t set up to handle both at once.' },
      { type: 'p', text: 'This article is for the family members who are trying to figure out what to actually do, not the theoretical answer, but the practical one.' },
      { type: 'h2', text: 'Understanding the Relationship Between the Two' },
      { type: 'p', text: 'The relationship between mental health conditions and substance use disorders is bidirectional and complex. Substance use worsens psychiatric symptoms: heavy alcohol use deepens depression, stimulants worsen anxiety and can trigger psychosis, cannabis in vulnerable individuals can accelerate psychotic illness. Mental health conditions also increase the risk of substance use, and people with PTSD, bipolar disorder, schizophrenia, and severe depression all show significantly elevated rates of addiction, often (though not always) in patterns consistent with self-medication.' },
      { type: 'p', text: 'What this means practically is that treating one condition while ignoring the other almost always fails. The untreated condition will undermine recovery from the treated one. This is not a theory. It\'s the consistent finding across decades of research on this population.' },
      { type: 'h2', text: 'The Most Common Mistake Families Make' },
      { type: 'p', text: 'The most common mistake I see families make is prioritizing one diagnosis over the other, usually the one that feels most urgent or most familiar. "Let\'s get him sober first, then we\'ll deal with the depression." Or: "The real issue is the bipolar. If we can get that stabilized, the drinking will take care of itself."' },
      { type: 'p', text: 'Both of these framings are understandable. Both tend to produce the same outcome: failed treatment, because the untreated condition reasserts itself and undoes the progress made on the other.' },
      { type: 'h2', text: 'Why Motivational Interviewing Matters Here' },
      { type: 'p', text: 'People with dual diagnoses are, as a group, more ambivalent about treatment than people with single diagnoses, often because previous treatment has failed them or addressed only part of their presentation. Motivational Interviewing (MI) is particularly important in this context because it meets people where they are, honors their ambivalence, and builds intrinsic motivation rather than demanding compliance.' },
      { type: 'p', text: 'For families, the MI framework offers practical guidance: resist the urge to argue, confront, or lecture. Express empathy. Reflect what your loved one says about wanting their life to be different. Ask open questions about what they value and what\'s getting in the way. You are not trying to win an argument. You are trying to stay in relationship with someone who is struggling, while gently supporting movement toward help.' },
      { type: 'h2', text: 'DBT: Built for This Population' },
      { type: 'p', text: 'Dialectical Behavior Therapy (DBT), developed by Marsha Linehan, was originally created for individuals with borderline personality disorder, a population with very high rates of co-occurring substance use. DBT has since been adapted and validated across a wide range of dual diagnosis presentations. Its core focus on emotional regulation, distress tolerance, mindfulness, and interpersonal effectiveness directly addresses many of the vulnerabilities that drive both psychiatric symptoms and substance use.' },
      { type: 'p', text: 'Linehan\'s research on DBT adapted specifically for substance use disorders found significant reductions in both drug use and suicidal behavior in a population for whom most other interventions had failed. For individuals whose substance use is heavily driven by emotional dysregulation, using to escape, numb, or manage overwhelming internal states, DBT offers tools that address the root function of the behavior, not just the behavior itself.' },
      { type: 'h2', text: 'Finding the Right Treatment, and What That Actually Takes' },
      { type: 'p', text: 'Integrated treatment, treating both conditions simultaneously with a coordinated team, is the evidence-based standard. But genuinely integrated dual diagnosis programs are not as common as they claim to be. The phrase "dual diagnosis capable" is used by programs with very different levels of actual capability. Evaluating whether a program can genuinely hold the complexity of a specific presentation requires knowing what questions to ask and how to evaluate the answers.' },
      { type: 'p', text: 'For families trying to navigate this: you are not expected to know which programs can actually handle your loved one\'s specific combination of diagnoses. That\'s specialized knowledge. It\'s what we do every day.' },
      { type: 'h2', text: 'Taking Care of Yourself' },
      { type: 'p', text: 'The research on family burden in dual diagnosis situations is significant. Caring for someone with co-occurring disorders carries higher caregiver burden, higher rates of family member depression and anxiety, and more severe family disruption than either condition alone. This is not sustainable without support.' },
      { type: 'p', text: 'Getting support for yourself, through NAMI family programs, Al-Anon, CRAFT-based family work, or individual therapy, is not a luxury. It\'s a clinical necessity for anyone in this situation long-term. You cannot effectively support someone else\'s recovery while depleting your own resources.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'If you\'re supporting a loved one with co-occurring disorders and you\'re not sure where to turn, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'SAMHSA TIP 42 (2005). Substance abuse treatment for persons with co-occurring disorders. Substance Abuse and Mental Health Services Administration.',
      'Drake, R.E., et al. (2001). Implementing dual diagnosis services for clients with severe mental illness. Psychiatric Services, 52(4), 469-476.',
      'Linehan, M.M., et al. (2002). Dialectical behavior therapy versus comprehensive validation therapy plus 12-step for opioid dependent women with borderline personality disorder. Drug and Alcohol Dependence, 67(1), 13-26.',
      'Miller, W.R. & Rollnick, S. (2013). Motivational Interviewing: Helping People Change (3rd ed.). Guilford Press.',
      'NAMI (2023). Dual Diagnosis: Mental Illness and Substance Use Disorders. National Alliance on Mental Illness.',
    ],
  },

  {
    slug: 'sober-companion-vs-recovery-coach',
    title: 'Sober Companion vs. Recovery Coach: What\'s the Difference and Which Do You Need?',
    author: 'Jack Foley, LMFT | Holistic Solutions',
    excerpt: 'If you\'ve looked into post-treatment support options, you\'ve probably encountered both terms: sober companion and recovery coach. They\'re often used interchangeably. They\'re not the same thing, and understanding the difference matters for choosing the right support.',
    metaDescription: 'Sober companions and recovery coaches provide different support. Key differences, when each is appropriate, and how both fit a recovery plan.',
    date: '2026-03-02',
    category: 'Clinical Insights',
    image: null,
    relatedServices: ['recovery-coaching', 'companionship-support'],
    body: [
      { type: 'p', text: 'If you\'ve looked into post-treatment support options, you\'ve probably encountered both terms: sober companion and recovery coach. They\'re often used interchangeably. They\'re not the same thing, and the distinction matters when you\'re trying to build the right support structure for someone in early recovery.' },
      { type: 'h2', text: 'What a Sober Companion Is' },
      { type: 'p', text: 'A sober companion provides intensive, real-world support to someone in early recovery, typically someone who has recently completed a residential treatment program or who is at high risk of relapse. The role is often intensive and proximate: a sober companion may live with a client, accompany them to appointments, social situations, work, and travel, and be available around the clock during particularly high-risk periods.' },
      { type: 'p', text: 'The sober companion model emerged largely from the entertainment and high-net-worth world, where clients needed to return immediately to high-pressure, high-exposure environments where substances were readily available, and where the ordinary support structures of IOP or sober living weren\'t compatible with professional obligations. The intensity of the role is calibrated to the intensity of the risk.' },
      { type: 'p', text: 'Sober companions are not typically licensed clinicians. The quality of sober companion services varies enormously, from individuals with personal recovery experience and deep practical wisdom to those with little more than a personal history. When evaluating a sober companion, it\'s important to understand their background, their approach to crisis, and how they communicate with the clinical team overseeing the client\'s care.' },
      { type: 'h2', text: 'What a Recovery Coach Is' },
      { type: 'p', text: 'A recovery coach, sometimes called a recovery support specialist or peer support specialist, provides structured, skills-based support to someone navigating the recovery process. The coaching relationship is less intensive and more structured than a sober companion arrangement, typically involving regular scheduled contact, goal-setting, accountability check-ins, and practical skill-building.' },
      { type: 'p', text: 'Recovery coaching draws on principles from both peer support research and professional coaching frameworks. The focus is on building the person\'s own skills and resources for sustaining recovery, not just managing immediate risk, but building the life structures and internal capacities that make long-term recovery possible. Acceptance and Commitment Therapy (ACT)-informed coaching approaches help individuals clarify their values, commit to valued action, and develop psychological flexibility in the face of cravings, setbacks, and difficult emotions.' },
      { type: 'h2', text: 'The Key Differences' },
      { type: 'p', text: 'The core difference is intensity and structure. Sober companions provide high-intensity, often around-the-clock proximity support, typically in the immediate post-treatment period or during high-risk transitions. Recovery coaches provide lower-intensity, more structured support over a longer period, focused on skill-building and sustained progress.' },
      { type: 'p', text: 'A second meaningful difference is the time horizon. Sober companion engagements are typically short-term, weeks to a few months. Recovery coaching relationships often extend for six months to a year or more, providing continuity through the full arc of early recovery rather than just the acute transition.' },
      { type: 'h2', text: 'What the Research Says About Peer Support in Recovery' },
      { type: 'p', text: 'The evidence base for peer support in recovery has grown substantially. Research by William White and colleagues on recovery management emphasizes that long-term recovery is supported by sustained community connection, meaningful roles, and relationships with others in recovery, all of which peer-based recovery support can provide. A SAMHSA review of peer support services found consistent positive effects on engagement in treatment, reduction in substance use, and improvement in quality of life outcomes.' },
      { type: 'p', text: 'What the research also makes clear is that peer support works best when it is integrated into a broader recovery plan that includes clinical oversight. Peer support without clinical coordination can miss clinical developments that require professional response. The most effective continuing care configurations combine clinical case management, which maintains the clinical picture and adjusts the plan as needed, with recovery coaching or sober companion support on the ground.' },
      { type: 'h2', text: 'When Each Is Appropriate' },
      { type: 'p', text: 'A sober companion is most appropriate when: someone is in the immediate post-treatment period with high relapse risk, when the environment they\'re returning to is high-exposure or high-pressure, when psychiatric complexity is high enough that real-time support is clinically indicated, or when previous attempts at recovery have broken down in the transition period.' },
      { type: 'p', text: 'A recovery coach is most appropriate when: someone has achieved initial stability and is building the foundations of a longer-term recovery, when structured accountability and skill-building support over time is what\'s needed, and when the clinical situation doesn\'t require around-the-clock proximity but benefits from consistent human connection and structure.' },
      { type: 'h2', text: 'What We Offer' },
      { type: 'p', text: 'Our companionship and recovery coaching services are built on the recognition that early recovery is won or lost in the real world, not in the clinician\'s office. We provide recovery support that is informed by clinical oversight, coordinated with the full care team, and calibrated to the specific person and their specific risk profile. It\'s not a generic program. It\'s built around what this person actually needs to stay well.' },
      { type: 'bio', text: 'Jack Foley is a Licensed Marriage and Family Therapist and founder of Holistic Solutions, a clinical case management practice serving individuals and families nationwide. He specializes in substance use disorders, co-occurring conditions, and psychosis.' },
      { type: 'cta-link', text: 'To learn more about our recovery coaching and companionship services, ', linkText: 'contact us for a confidential consultation', href: '/contact', suffix: '.' },
    ],
    references: [
      'SAMHSA (2015). Peer support and social inclusion. Substance Abuse and Mental Health Services Administration.',
      'White, W.L. (2009). Peer-based addiction recovery support: history, theory, practice, and scientific evaluation. Great Lakes Addiction Technology Transfer Center.',
      'Jason, L.A., et al. (2006). A randomized trial of Oxford House. Journal of Consulting and Clinical Psychology, 74(2), 272-281.',
      'Hayes, S.C., et al. (2012). Acceptance and Commitment Therapy: The Process and Practice of Mindful Change (2nd ed.). Guilford Press.',
      'Tracy, K. & Wallace, S.P. (2016). Benefits of peer support groups in the treatment of addiction. Substance Abuse and Rehabilitation, 7, 143-154.',
    ],
  },
]

export function getPostBySlug(slug) {
  return posts.find((p) => p.slug === slug) || null
}
