export const services = [
  {
    slug: 'substance-use',
    num: '01',
    shortTitle: 'Substance Use',
    title: 'Substance Use Case Management',
    tagline: 'Coordinated, compassionate case management for alcohol and drug use disorders, across every level of care, anywhere in the country.',
    metaDescription: 'Clinical case management for substance use disorders. Assessment, treatment coordination, and ongoing support nationwide. Call (702) 494-7641.',
    keywords: 'substance use case management, addiction case manager, alcohol use disorder help, drug addiction case management, recovery support nationwide, substance abuse help Los Angeles',
    definition: 'Substance use case management is a clinical service in which a licensed clinician assesses an individual with a substance use disorder, builds a personalized treatment plan, and coordinates care across detox, residential, PHP, IOP, and outpatient programs nationwide.',
    faqs: [
      { q: 'What is substance use case management?', a: 'Substance use case management is a clinical service where a licensed clinician assesses someone with a substance use disorder, builds a personalized care plan, and coordinates treatment across every level of care — detox, residential, PHP, IOP, and outpatient — adjusting the plan as the situation evolves.' },
      { q: 'How is a substance use case manager different from a therapist or sponsor?', a: 'A therapist provides clinical treatment in scheduled sessions. A sponsor provides peer support inside a 12-step framework. A case manager coordinates the entire system of care: assessing what is needed, placing the person in the right program, communicating with providers, and managing transitions. The case manager works above the providers, not in place of them.' },
      { q: 'Do you only work with people in active addiction, or also with families?', a: 'Both. Many of our cases begin with a family who does not know what to do. We assess the full clinical picture, advise on next steps, and remain involved through placement and aftercare. When the individual is not yet ready, we work with the family on strategy and, when appropriate, coordinate a clinical intervention.' },
      { q: 'Do you accept insurance for substance use case management?', a: 'Case management itself is typically a private-pay service. The treatment programs we coordinate (detox, residential, PHP, IOP) are often covered by insurance, and we handle verification and pre-authorization on your behalf as part of the coordination work.' },
      { q: 'Can substance use case management help with co-occurring mental health conditions?', a: 'Yes — co-occurring presentations are the norm in the cases we see. We coordinate substance use and mental health care as a single integrated plan rather than two parallel tracks. See our co-occurring disorders case management service for more detail.' },
    ],
    overview: [
      'Substance use disorders are rarely straightforward. They involve biology, history, relationships, trauma, and environment, all at once. Cookie-cutter treatment plans don\'t work for complex people, and our clients are complex people.',
      'Our substance use case management begins with a thorough biopsychosocial assessment. We look at the full picture: what substances, what patterns, what co-occurring conditions, what family dynamics, what\'s been tried before and why it didn\'t work. From there, we build a care plan that actually fits.',
      'We coordinate across every level of care: medical detox, residential treatment, partial hospitalization (PHP), intensive outpatient (IOP), and ongoing outpatient support. We stay involved throughout, adjusting the plan as your situation evolves and advocating for you when the system pushes back.',
    ],
    whoItHelps: [
      'Individuals in active addiction seeking a clear path forward',
      'Families who don\'t know where to start or have tried before without lasting results',
      'People who have been through treatment and need stronger coordination this time',
      'Executives and professionals seeking discreet, private support',
      'Individuals navigating co-occurring mental health conditions alongside substance use',
    ],
    whatToExpect: [
      { title: 'Assessment', body: 'A comprehensive clinical evaluation covering substance use history, mental health, medical factors, social support, and prior treatment experiences.' },
      { title: 'Care Plan', body: 'A personalized, goal-oriented treatment plan built around your specific clinical needs, preferences, and life circumstances.' },
      { title: 'Placement & Coordination', body: 'We identify and place you in the right level of care, detox, residential, PHP, IOP, or outpatient, from our vetted national network.' },
      { title: 'Ongoing Support', body: 'We stay with you through treatment, monitoring progress, managing transitions, and adjusting the plan when life changes.' },
    ],
    differentiator: 'Substance use disorders and psychosis are where our clinical roots run deepest. This is not a service we offer alongside other things. It\'s the foundation our practice was built on. Jack Foley, LMFT, brings both personal and professional experience to every case, and that combination is rare.',
  },
  {
    slug: 'mental-health',
    num: '02',
    shortTitle: 'Mental Health',
    title: 'Mental Health Case Management',
    tagline: 'Expert coordination for depression, anxiety, trauma, PTSD, psychosis, and beyond, connecting you with clinicians who actually specialize in what you\'re facing.',
    metaDescription: 'Case management for depression, anxiety, trauma, PTSD, and psychosis. We connect you with the right specialists, nationwide. Confidential.',
    keywords: 'mental health case management, psychosis case manager, depression anxiety case management, PTSD case manager, mental health coordination nationwide',
    definition: 'Mental health case management is a clinical service in which a licensed clinician assesses a person\'s psychiatric needs and matches them with therapists, psychiatrists, and treatment programs that genuinely specialize in their condition — including complex presentations like psychosis, treatment-resistant depression, and trauma-related disorders.',
    faqs: [
      { q: 'What is mental health case management?', a: 'Mental health case management is a clinical service in which a licensed clinician assesses a person\'s psychiatric needs and matches them with the right therapists, psychiatrists, and treatment programs — particularly important for complex conditions like psychosis, treatment-resistant depression, and trauma-related disorders.' },
      { q: 'Why is provider matching so important in mental health?', a: 'Mental health care is highly specialized. A psychiatrist who is excellent for mood disorders may not be the right person for first-episode psychosis. A trauma therapist trained in EMDR is different from one trained in IFS. Matching the right clinician to the specific presentation often determines whether treatment works or stalls.' },
      { q: 'Do you specialize in psychosis or first-episode psychosis?', a: 'Yes. Psychosis and first-episode psychosis are core areas of expertise for our practice. Many providers lack training in psychotic disorders, which leaves families without good options. We know which programs and clinicians actually specialize in this work.' },
      { q: 'Can a mental health case manager work with someone who refuses care?', a: 'Yes. We work with families on strategy when a loved one is not yet willing to engage. When appropriate, we coordinate a clinical intervention led by a master\'s-level licensed clinician — not a certified interventionist — which matters when psychiatric complexity is in the picture.' },
      { q: 'Is mental health case management nationwide?', a: 'Yes. We serve clients in all 50 states. Assessment, care coordination, and provider matching are all available remotely, with in-person services coordinated through our local networks where they exist.' },
    ],
    overview: [
      'Mental health care in the United States is fragmented. Finding the right therapist, psychiatrist, or treatment program for your specific condition, not just any condition, requires time, knowledge, and connections that most people don\'t have. That\'s where we come in.',
      'We specialize in matching clients with clinicians who are genuinely expert in what they\'re facing. For complex presentations like psychosis, trauma-related disorders, or treatment-resistant depression, this matching process is critical and often the difference between progress and another dead end.',
      'Psychosis, in particular, is one of the most under-supported presentations in behavioral health. Many providers lack the training and experience to work with it effectively. Holistic Solutions was built in part around these cases. It\'s where our clinical depth runs deepest.',
    ],
    whoItHelps: [
      'Individuals struggling with depression, anxiety, or mood disorders',
      'People experiencing psychosis or a first psychiatric break',
      'Trauma and PTSD survivors navigating care for the first time or after failed treatment',
      'Families supporting a loved one with a serious mental illness',
      'Anyone who has seen multiple providers without finding the right fit',
    ],
    whatToExpect: [
      { title: 'Clinical Assessment', body: 'We assess the full scope of mental health needs, history, and treatment responses to understand what has and hasn\'t worked.' },
      { title: 'Provider Matching', body: 'We identify therapists, psychiatrists, and treatment programs specifically qualified for your presentation, not just anyone who accepts your insurance.' },
      { title: 'Care Coordination', body: 'We manage communication between all providers, ensure continuity of care, and advocate for your needs at every level.' },
      { title: 'Monitoring & Adjustment', body: 'Mental health care requires ongoing attention. We stay involved and adjust the plan as your condition evolves.' },
    ],
    differentiator: 'Psychosis and complex psychiatric presentations are where we have built our deepest expertise. We understand the clinical nuances that most case managers miss, and that understanding translates into better outcomes for the people we serve.',
  },
  {
    slug: 'co-occurring-disorders',
    num: '03',
    shortTitle: 'Co-Occurring Disorders',
    title: 'Co-Occurring Disorders Case Management',
    tagline: 'Integrated care planning for individuals navigating both substance use and mental health challenges, addressed together, not separately.',
    metaDescription: 'Integrated case management for co-occurring disorders and dual diagnosis. Substance use and mental health addressed together. Nationwide.',
    keywords: 'co-occurring disorders case management, dual diagnosis case manager, integrated treatment planning, substance use mental health, dual diagnosis support nationwide',
    definition: 'Co-occurring disorders case management — also called dual diagnosis case management — is an integrated clinical service that addresses substance use and mental health conditions in a single coordinated plan, rather than treating them as separate problems handed off between specialties.',
    faqs: [
      { q: 'What are co-occurring disorders?', a: 'Co-occurring disorders (also called dual diagnosis) describe the simultaneous presence of a substance use disorder and a mental health condition — for example, depression with alcohol use disorder, or PTSD with opioid use disorder. The majority of people with a substance use disorder also live with a mental health condition.' },
      { q: 'Why does dual diagnosis often need integrated case management?', a: 'Treating one condition without the other is one of the most common reasons treatment fails. Integrated case management ensures the substance use and mental health pieces are addressed as a single, coordinated plan with providers who communicate, rather than two parallel tracks that miss each other.' },
      { q: 'How do you handle providers across both specialties?', a: 'We assemble a team that includes the right substance use specialists and the right psychiatric providers, align them on shared treatment goals, and manage communication so nothing falls through the cracks between disciplines.' },
      { q: 'Is dual diagnosis case management available nationwide?', a: 'Yes. Co-occurring case management is one of our most-requested services and is available in all 50 states. We also have dedicated dual diagnosis pages for Las Vegas, Los Angeles, and New York City clients.' },
      { q: 'What conditions commonly co-occur with substance use?', a: 'Depression, anxiety, trauma and PTSD, bipolar disorder, ADHD, and psychotic disorders are the conditions we see most frequently alongside substance use. The combination of substances and underlying psychiatric conditions changes the clinical picture considerably and requires care planning that holds both in view.' },
    ],
    overview: [
      'The majority of people with a substance use disorder also live with a mental health condition. Depression, anxiety, trauma, PTSD, bipolar disorder, and psychosis frequently co-occur with addiction. Treating one without addressing the other is one of the most common reasons treatment fails.',
      'Co-occurring disorders require a clinician who understands both sides of the picture simultaneously. Not a substance use specialist who treats mental health as secondary, and not a mental health provider who minimizes addiction. Someone who holds both.',
      'Our integrated case management approach ensures that your treatment plan addresses substance use and mental health as interconnected, because they are. We coordinate providers, align treatment goals, and make sure nothing falls through the cracks between specialties.',
    ],
    whoItHelps: [
      'Individuals who have struggled with both addiction and mental health challenges',
      'People whose mental health symptoms have intensified with substance use',
      'Those who have been treated for one condition but not both',
      'Families navigating a loved one with a complex dual diagnosis',
      'Anyone who has had treatment fail because the full picture wasn\'t addressed',
    ],
    whatToExpect: [
      { title: 'Integrated Assessment', body: 'A comprehensive evaluation that examines both substance use and mental health simultaneously, identifying how each influences the other.' },
      { title: 'Unified Care Plan', body: 'A single, coordinated plan that addresses both conditions, not two separate plans that don\'t talk to each other.' },
      { title: 'Dual-Track Coordination', body: 'We manage relationships with providers across both specialties, ensuring they are aligned and communicating.' },
      { title: 'Ongoing Monitoring', body: 'We track progress across both dimensions and adjust the plan in real time as your needs change.' },
    ],
    differentiator: 'Co-occurring presentations are not a specialty add-on for us. They are the norm in the cases we see. Our clinical team is trained to hold both the substance use and the psychiatric complexity in view at all times, which is what effective dual-diagnosis care actually requires.',
  },
  {
    slug: 'intervention-services',
    num: '04',
    shortTitle: 'Clinical Intervention Services',
    title: 'Clinical Intervention Services',
    tagline: 'Interventions led by masters-level licensed clinicians, not just certified interventionists. When psychiatric complexity is part of the picture, clinical training isn\'t optional.',
    metaDescription: 'Clinical interventions led by master\'s-level licensed clinicians. For substance use and psychiatric crises. Nationwide. Call (702) 494-7641.',
    keywords: 'clinical intervention services, masters level interventionist, addiction intervention Los Angeles, family intervention services, licensed clinician intervention, psychiatric intervention',
    definition: 'A clinical intervention is a structured family meeting led by a master\'s-level licensed clinician designed to help a loved one accept treatment for substance use or a psychiatric condition, with treatment placement coordinated in advance so admission can happen the same day.',
    faqs: [
      { q: 'What is a clinical intervention?', a: 'A clinical intervention is a structured family meeting led by a master\'s-level licensed clinician designed to help a loved one accept treatment for substance use or a psychiatric condition. Treatment placement is coordinated in advance so the person can be admitted the same day if they say yes.' },
      { q: 'What\'s the difference between a clinical interventionist and a certified interventionist?', a: 'A certified interventionist is trained in the structure and process of intervention. A clinical interventionist is also a licensed clinician — typically a master\'s-level therapist — who can read clinical complexity in real time, recognize an emerging psychiatric crisis, and respond to trauma reactions safely. When mental health is part of the picture, that clinical training matters.' },
      { q: 'How do interventions work when someone has both substance use and a mental illness?', a: 'These cases are exactly where clinical training becomes essential. We assess the psychiatric picture beforehand, plan for the possibility of psychiatric escalation in the room, and coordinate treatment placement at programs equipped for co-occurring presentations rather than substance-use-only facilities.' },
      { q: 'What happens if my loved one says no?', a: 'Saying no in the room is not the end. Most successful outcomes involve continued family work after the meeting, with the case manager guiding next steps. Sometimes the person agrees days or weeks later. We stay involved and continue to support the family through the longer process.' },
      { q: 'Do you provide clinical interventions nationwide?', a: 'Yes. We travel for clinical interventions throughout the United States. We also coordinate immediate treatment placement at vetted programs anywhere in the country.' },
    ],
    overview: [
      'Most intervention services are led by certified interventionists, people trained in the process and structure of intervention. That training is valuable. But it has limits.',
      'When a loved one\'s mental health, trauma history, or psychiatric state is part of the picture, and it often is, you need someone who can read the room clinically. Someone who can recognize an emerging psychiatric crisis, respond to a trauma response in real time, and navigate complexity that goes beyond what a script can anticipate.',
      'Holistic Solutions interventions are led by licensed, masters-level clinicians. That distinction matters. We assess what\'s actually happening in the room, adapt in real time, and manage the full complexity of what unfolds, including immediate placement coordination when your loved one says yes.',
    ],
    whoItHelps: [
      'Families of someone who has refused help and needs structured support to accept it',
      'Situations involving co-occurring mental health and substance use',
      'Cases with trauma history or psychiatric complexity',
      'Families who have attempted an intervention before without success',
      'Situations requiring immediate placement following the intervention',
    ],
    whatToExpect: [
      { title: 'Pre-Intervention Planning', body: 'We work closely with the family to understand the full clinical picture, structure the intervention, and prepare everyone involved.' },
      { title: 'Clinical Facilitation', body: 'A licensed clinician leads the intervention, assessing what\'s happening in real time and guiding the process through complexity.' },
      { title: 'Immediate Placement', body: 'When your loved one agrees to get help, we move immediately. Treatment placement is coordinated in advance so there is no gap.' },
      { title: 'Family Support', body: 'We support the family throughout, before, during, and after, because intervention affects the whole system, not just the individual.' },
    ],
    differentiator: 'The difference between a certified interventionist and a licensed clinician is the difference between knowing the process and being clinically trained. When things go sideways, and in complex cases they often do, clinical training is what allows us to keep the intervention on track and keep everyone safe.',
  },
  {
    slug: 'treatment-placement',
    num: '05',
    shortTitle: 'Treatment Placement',
    title: 'Treatment Placement Services',
    tagline: 'We identify, vet, and place clients in the most appropriate programs nationwide. No guessing. No cold calls. The right fit, fast.',
    metaDescription: 'We identify, vet, and place clients in the right treatment programs nationwide. Detox, residential, PHP, IOP, outpatient. No cold calls.',
    keywords: 'treatment placement services, find rehab nationwide, addiction treatment placement, residential treatment placement, detox placement, PHP IOP placement, behavioral health placement',
    definition: 'Treatment placement is a clinical service in which a licensed clinician matches an individual to a vetted behavioral health program — detox, residential, PHP, IOP, or outpatient — based on clinical fit, then handles insurance verification, admissions, and logistics so the person can enter care quickly.',
    faqs: [
      { q: 'What is treatment placement?', a: 'Treatment placement is a clinical service in which a licensed clinician matches a person to a vetted treatment program (detox, residential, PHP, IOP, or outpatient), then manages insurance verification, admissions, and travel logistics so the person can enter care without delay.' },
      { q: 'How is treatment placement different from a referral?', a: 'A referral usually means a name and phone number. Placement means active matching to a program we have personally evaluated, communication with the admissions team on your behalf, insurance work, and coordination of arrival. Placement is hands-on; referral is a handoff.' },
      { q: 'Do you have relationships with treatment programs nationwide?', a: 'Yes. We have personally evaluated hundreds of programs across the country and maintain a vetted national network. We do not place people into programs we have not assessed.' },
      { q: 'How fast can placement happen?', a: 'When someone is ready for treatment, waiting is dangerous. We work in hours, not days, when the situation calls for it — assessing, identifying options, verifying insurance, and arranging admission as quickly as the receiving program allows.' },
      { q: 'What if the first program isn\'t the right fit?', a: 'Placement does not end at admission. We monitor progress, manage transitions between levels of care, and help reposition someone if the initial program is not delivering what they need. Continuity of oversight is part of the service.' },
    ],
    overview: [
      'Searching for treatment on your own means cold-calling programs, navigating sales pitches, and trying to evaluate clinical quality without the knowledge to do it. It is exhausting, and the wrong placement costs time, money, and momentum.',
      'We have spent years building and vetting a national network of treatment programs across every level of care. We know which programs have strong clinical staff, which ones actually specialize in what your loved one is facing, and which ones to avoid. When we make a placement, it\'s purposeful, not random.',
      'Our placement process moves fast. When someone is ready for treatment, waiting is dangerous. We work quickly to identify the right options, verify insurance or arrange private pay, and get your loved one through the door with as little friction as possible.',
    ],
    whoItHelps: [
      'Individuals ready to enter treatment who don\'t know where to go',
      'Families overwhelmed by the number of options and the quality gap between programs',
      'People who have been to treatment before and need a better fit this time',
      'Cases requiring specialized programming, including trauma, psychosis, dual diagnosis, or executive needs',
      'Situations requiring immediate placement after an intervention or crisis',
    ],
    whatToExpect: [
      { title: 'Needs Assessment', body: 'We clarify clinical needs, budget, location preferences, and any special requirements before identifying programs.' },
      { title: 'Program Matching', body: 'We identify and present the best-fit options from our vetted national network, explaining the clinical rationale for each.' },
      { title: 'Insurance & Logistics', body: 'We verify coverage, handle pre-authorization, coordinate admissions, and manage the logistics of getting there.' },
      { title: 'Transition Support', body: 'Placement doesn\'t end at admission. We monitor progress and manage transitions through each level of care.' },
    ],
    differentiator: 'We have personally evaluated hundreds of programs. We do not refer from a list. We place with purpose, drawing on relationships and firsthand knowledge built over years of clinical work in this field.',
  },
  {
    slug: 'recovery-coaching',
    num: '06',
    shortTitle: 'Recovery Coaching',
    title: 'Recovery Coaching',
    tagline: 'Ongoing one-on-one coaching for individuals in active recovery, building the accountability, structure, and skills needed for lasting sobriety and mental wellness.',
    metaDescription: 'One-on-one recovery coaching for individuals in active recovery. Accountability, structure, and relapse prevention. Nationwide support.',
    keywords: 'recovery coaching, sober coaching, addiction recovery coach, relapse prevention coaching, sober support nationwide, recovery accountability coach',
    definition: 'Recovery coaching is ongoing one-on-one support — separate from therapy — that focuses on the practical work of living in recovery: daily structure, accountability, relapse prevention, and navigating real-world challenges with someone who knows what sustainable sobriety actually requires.',
    faqs: [
      { q: 'What is recovery coaching?', a: 'Recovery coaching is ongoing one-on-one support focused on the practical work of living in recovery — daily structure, accountability, skill-building, relapse prevention, and navigating real-world challenges. It is distinct from therapy and from peer sponsorship.' },
      { q: 'Is a recovery coach the same as a therapist?', a: 'No. A therapist treats clinical conditions in scheduled sessions. A recovery coach is an active, in-your-corner support person focused on the day-to-day mechanics of staying in recovery. Many people work with both at once.' },
      { q: 'Is a recovery coach the same as a sponsor?', a: 'No. A sponsor is a peer in a 12-step program supporting another peer through the steps. A recovery coach is a paid professional with training in recovery, behavior change, and clinical principles, working independently of any specific recovery program.' },
      { q: 'Who benefits most from recovery coaching?', a: 'People newly out of residential treatment, people in early recovery who want consistent accountability, professionals managing high-stress careers alongside sobriety, and anyone who has relapsed and wants a stronger structural support this time.' },
      { q: 'Is recovery coaching available remotely?', a: 'Yes. Recovery coaching is delivered remotely (phone and video) with optional in-person sessions where geography allows. We work with clients nationwide.' },
    ],
    overview: [
      'Completing treatment is a milestone, not a finish line. The period immediately following discharge is often the highest-risk time in a person\'s recovery. Structure disappears, triggers reappear, and the support that existed in treatment is suddenly gone.',
      'Recovery coaching fills that gap. It is ongoing, one-on-one support from someone who knows recovery, its rhythms, its hard moments, and what it actually takes to build a life that works.',
      'Our coaching focuses on the practical: daily structure, accountability, skill-building, relapse prevention planning, and navigating the real-world challenges that arise in early and ongoing recovery. This is not therapy. It\'s active, in-your-corner support from someone invested in your success.',
    ],
    whoItHelps: [
      'Individuals newly out of residential treatment navigating the transition home',
      'People in early recovery who want accountability and structured support',
      'Those managing a high-stress professional life alongside sobriety',
      'Anyone who has relapsed and wants a stronger support structure this time',
      'Individuals in long-term recovery navigating a significant life change or stressor',
    ],
    whatToExpect: [
      { title: 'Initial Session', body: 'We establish recovery goals, identify high-risk situations, and build a personalized coaching plan tailored to your life.' },
      { title: 'Regular Check-ins', body: 'Consistent scheduled sessions to review progress, troubleshoot challenges, and reinforce accountability.' },
      { title: 'Real-Time Support', body: 'Access to your coach during high-risk moments, not just scheduled sessions.' },
      { title: 'Long-Term Planning', body: 'We help build the habits, relationships, and daily structures that support lasting sobriety, not just short-term stability.' },
    ],
    differentiator: 'Our coaching is grounded in clinical understanding. We are not simply cheerleaders. We understand the neuroscience of addiction, the patterns of relapse, and the clinical factors that make recovery sustainable. That knowledge shapes every coaching relationship.',
  },
  {
    slug: 'companionship-support',
    num: '07',
    shortTitle: 'Companionship & Support',
    title: 'Companionship & Support Services',
    tagline: 'In-person support during high-risk moments, treatment transitions, or whenever a trusted, clinical presence is needed most.',
    metaDescription: 'In-person clinical companionship during treatment transitions and high-risk moments. Trained, supervised support when it matters most.',
    keywords: 'sober companion, clinical companion services, addiction companion, in-person recovery support, sober escort, companionship services behavioral health',
    definition: 'Clinical companionship is in-person support from a trained, clinically-supervised companion who is physically present with a person during high-risk moments — treatment transitions, triggering events, or unstable periods — providing active, attentive support rather than passive presence.',
    faqs: [
      { q: 'What is a clinical companion?', a: 'A clinical companion is a trained, clinically-supervised support professional who is physically present with a person during high-risk moments — treatment transitions, triggering events, or unstable periods — providing active and attentive support rather than passive presence.' },
      { q: 'How is this different from a sober companion?', a: 'A sober companion is typically a peer with lived experience in recovery. A clinical companion is also clinically trained and supervised — they understand behavioral patterns, risk factors, and how to respond to escalating situations. Our companions operate inside a clinical framework with ongoing case oversight.' },
      { q: 'When does someone benefit from a companion?', a: 'Common moments include the first weeks after residential treatment, attending high-stress events in early recovery, traveling through high-risk environments, or any unstable period where consistent in-person presence would meaningfully reduce risk.' },
      { q: 'How long does a companion stay?', a: 'Engagements range from a single day or weekend to multi-week placements. Duration is matched to the situation and reviewed regularly. Companion services can also be integrated into a broader case management plan.' },
      { q: 'Are companion services available outside major cities?', a: 'Yes. We deploy companions nationwide based on need. Travel and logistics are coordinated as part of the engagement.' },
    ],
    overview: [
      'Some moments in recovery require a real, present human being, not a phone call, not a session. Transitioning out of treatment, navigating a high-risk environment, attending a triggering event, or simply getting through a hard day are situations where in-person support makes a real difference.',
      'Our companion services provide exactly that: a trained, clinically-informed individual who is physically present with your loved one when it matters most. This is not babysitting. It is active, thoughtful support from someone who understands what\'s at stake.',
      'Companion services can be standalone or integrated into a broader case management plan. Duration and frequency are tailored to the specific situation and level of support needed.',
    ],
    whoItHelps: [
      'Individuals transitioning out of residential treatment into a less structured environment',
      'People navigating early recovery in a high-risk social environment',
      'Families who need temporary in-person support for a loved one between placements',
      'Individuals attending high-stress events (family gatherings, work situations) in early recovery',
      'Anyone whose recovery plan requires a consistent, present support figure',
    ],
    whatToExpect: [
      { title: 'Needs Assessment', body: 'We clarify the situation, the risk level, and the type of support that\'s most appropriate.' },
      { title: 'Matched Support', body: 'We match you with a companion whose background fits your specific needs and personality.' },
      { title: 'Active Presence', body: 'Your companion is engaged and attentive, not just physically present. They understand what to watch for and how to respond.' },
      { title: 'Coordination', body: 'Companion services are coordinated with the broader care plan, with regular communication to the case management team.' },
    ],
    differentiator: 'Our companions are not simply sober individuals with lived experience. They are trained, clinically-supervised support professionals who understand the behavioral patterns, risks, and needs specific to the individuals they serve.',
  },
  {
    slug: 'safe-transport',
    num: '08',
    shortTitle: 'Safe & Clinical Transport',
    title: 'Safe & Clinical Transport',
    tagline: 'Supervised, compassionate transport to treatment facilities, appointments, and step-down programs, ensuring your loved one arrives safely and supported.',
    metaDescription: 'Supervised, compassionate transport to treatment facilities and appointments. Clinically informed team. Nationwide. Confidential.',
    keywords: 'safe clinical transport, addiction transport services, escort to treatment, transport to rehab, clinical transport behavioral health, safe transport to detox',
    definition: 'Safe clinical transport is a supervised escort service in which a clinically-informed team member accompanies a person from their location to a treatment facility, appointment, or step-down program — managing the full journey, communicating with the receiving program, and staying present until handoff is complete.',
    faqs: [
      { q: 'What is safe clinical transport?', a: 'Safe clinical transport is a supervised escort service in which a clinically-informed team member accompanies a person to a treatment facility, appointment, or step-down program. We coordinate logistics in advance, communicate with the receiving program, and stay present until the handoff is complete.' },
      { q: 'Why use a clinical transport service instead of family or a rideshare?', a: 'The window between agreement and admission is fragile. The wrong transport experience — anxiety in an airport, time alone in a car, an unscheduled stop — can close it. A clinical escort is trained to hold space through that window and respond to escalation if it occurs.' },
      { q: 'Do you provide cross-country and air transport?', a: 'Yes. We coordinate flights, ground transport on both ends, and timing with the receiving program. Cross-state and cross-country transports are standard for us.' },
      { q: 'Is transport ever involuntary?', a: 'No. We provide supervised, supportive transport for individuals who have agreed to treatment. We do not perform involuntary transport and will refer families to appropriate resources when that is what is needed.' },
      { q: 'How do I arrange transport?', a: 'Call (702) 494-7641 or submit a contact form. We can usually arrange transport within 24–48 hours, faster when the situation requires it. All inquiries are confidential.' },
    ],
    overview: [
      'Getting a loved one from agreement to admission is often harder than it sounds. The window between "yes" and arrival at a treatment facility is fragile, and the wrong transport experience can close it.',
      'Our clinical transport service bridges that gap. We provide supervised, compassionate transport to treatment facilities, medical appointments, and step-down programs, ensuring your loved one is supported throughout the journey, not just handed off at the door.',
      'Every transport is managed by a clinically-informed team member who understands how to hold space during this transition. We communicate with the receiving facility in advance, manage the logistics, and stay present until handoff is complete.',
    ],
    whoItHelps: [
      'Families whose loved one has agreed to treatment and needs support getting there',
      'Individuals who need transport to a facility in another city or state',
      'People transitioning between levels of care (residential to PHP, PHP to IOP)',
      'Situations where flying or driving alone would be clinically inadvisable',
      'Anyone whose safety or commitment to treatment could be at risk during transit',
    ],
    whatToExpect: [
      { title: 'Logistics Coordination', body: 'We coordinate all transportation logistics, flights, ground transport, and arrival timing, in advance with the receiving facility.' },
      { title: 'Clinical Escort', body: 'A trained team member accompanies your loved one throughout the journey, providing support and stability.' },
      { title: 'Communication', body: 'We keep the family informed throughout the transport and confirm safe arrival.' },
      { title: 'Seamless Handoff', body: 'We coordinate directly with the admissions team to ensure a smooth, supported transition into care.' },
    ],
    differentiator: 'Clinical transport is not a taxi service with good intentions. Our team understands that the window between agreement and admission is clinically significant, and we treat it that way. Every transport is handled with the same care we bring to every aspect of our work.',
  },
]

export function getServiceBySlug(slug) {
  return services.find((s) => s.slug === slug)
}
