export const services = [
  {
    slug: 'substance-use',
    num: '01',
    shortTitle: 'Substance Use',
    title: 'Substance Use Case Management',
    tagline: 'Coordinated, compassionate case management for alcohol and drug use disorders — across every level of care, anywhere in the country.',
    metaDescription: 'Holistic Solutions provides clinical case management for substance use disorders including alcohol and drug addiction. Assessment, treatment coordination, and ongoing support nationwide.',
    keywords: 'substance use case management, addiction case manager, alcohol use disorder help, drug addiction case management, recovery support nationwide, substance abuse help Los Angeles',
    overview: [
      'Substance use disorders are rarely straightforward. They involve biology, history, relationships, trauma, and environment — all at once. Cookie-cutter treatment plans don\'t work for complex people, and our clients are complex people.',
      'Our substance use case management begins with a thorough biopsychosocial assessment. We look at the full picture: what substances, what patterns, what co-occurring conditions, what family dynamics, what\'s been tried before and why it didn\'t work. From there, we build a care plan that actually fits.',
      'We coordinate across every level of care — medical detox, residential treatment, partial hospitalization (PHP), intensive outpatient (IOP), and ongoing outpatient support. We stay involved throughout, adjusting the plan as your situation evolves and advocating for you when the system pushes back.',
    ],
    whoItHelps: [
      'Individuals in active addiction seeking a clear path forward',
      'Families who don\'t know where to start or have tried before without lasting results',
      'People who have been through treatment and need stronger coordination this time',
      'Executives and professionals seeking discreet, private support',
      'Individuals navigating co-occurring mental health conditions alongside substance use',
    ],
    whatToExpect: [
      { title: 'Assessment', body: 'A comprehensive clinical evaluation covering substance use history, mental health, medical factors, social support, and prior treatment experiences.' },
      { title: 'Care Plan', body: 'A personalized, goal-oriented treatment plan built around your specific clinical needs, preferences, and life circumstances.' },
      { title: 'Placement & Coordination', body: 'We identify and place you in the right level of care — detox, residential, PHP, IOP, or outpatient — from our vetted national network.' },
      { title: 'Ongoing Support', body: 'We stay with you through treatment, monitoring progress, managing transitions, and adjusting the plan when life changes.' },
    ],
    differentiator: 'Substance use disorders and psychosis are where our clinical roots run deepest. This is not a service we offer alongside other things — it\'s the foundation our practice was built on. Jack Foley, LMFT, brings both personal and professional experience to every case, and that combination is rare.',
  },
  {
    slug: 'mental-health',
    num: '02',
    shortTitle: 'Mental Health',
    title: 'Mental Health Case Management',
    tagline: 'Expert coordination for depression, anxiety, trauma, PTSD, psychosis, and beyond — connecting you with clinicians who actually specialize in what you\'re facing.',
    metaDescription: 'Clinical case management for mental health conditions including depression, anxiety, trauma, PTSD, and psychosis. Holistic Solutions connects clients nationwide with the right specialists.',
    keywords: 'mental health case management, psychosis case manager, depression anxiety case management, PTSD case manager, mental health coordination nationwide',
    overview: [
      'Mental health care in the United States is fragmented. Finding the right therapist, psychiatrist, or treatment program for your specific condition — not just any condition — requires time, knowledge, and connections that most people don\'t have. That\'s where we come in.',
      'We specialize in matching clients with clinicians who are genuinely expert in what they\'re facing. For complex presentations like psychosis, trauma-related disorders, or treatment-resistant depression, this matching process is critical and often the difference between progress and another dead end.',
      'Psychosis, in particular, is one of the most under-supported presentations in behavioral health. Many providers lack the training and experience to work with it effectively. Holistic Solutions was built in part around these cases — it\'s where our clinical depth runs deepest.',
    ],
    whoItHelps: [
      'Individuals struggling with depression, anxiety, or mood disorders',
      'People experiencing psychosis or a first psychiatric break',
      'Trauma and PTSD survivors navigating care for the first time or after failed treatment',
      'Families supporting a loved one with a serious mental illness',
      'Anyone who has seen multiple providers without finding the right fit',
    ],
    whatToExpect: [
      { title: 'Clinical Assessment', body: 'We assess the full scope of mental health needs, history, and treatment responses to understand what has and hasn\'t worked.' },
      { title: 'Provider Matching', body: 'We identify therapists, psychiatrists, and treatment programs specifically qualified for your presentation — not just anyone who accepts your insurance.' },
      { title: 'Care Coordination', body: 'We manage communication between all providers, ensure continuity of care, and advocate for your needs at every level.' },
      { title: 'Monitoring & Adjustment', body: 'Mental health care requires ongoing attention. We stay involved and adjust the plan as your condition evolves.' },
    ],
    differentiator: 'Psychosis and complex psychiatric presentations are where we have built our deepest expertise. We understand the clinical nuances that most case managers miss — and that understanding translates into better outcomes for the people we serve.',
  },
  {
    slug: 'co-occurring-disorders',
    num: '03',
    shortTitle: 'Co-Occurring Disorders',
    title: 'Co-Occurring Disorders Case Management',
    tagline: 'Integrated care planning for individuals navigating both substance use and mental health challenges — addressed together, not separately.',
    metaDescription: 'Specialized case management for co-occurring disorders and dual diagnosis. Holistic Solutions provides integrated treatment planning for substance use and mental health challenges nationwide.',
    keywords: 'co-occurring disorders case management, dual diagnosis case manager, integrated treatment planning, substance use mental health, dual diagnosis support nationwide',
    overview: [
      'The majority of people with a substance use disorder also live with a mental health condition. Depression, anxiety, trauma, PTSD, bipolar disorder, and psychosis frequently co-occur with addiction — and treating one without addressing the other is one of the most common reasons treatment fails.',
      'Co-occurring disorders require a clinician who understands both sides of the picture simultaneously. Not a substance use specialist who treats mental health as secondary, and not a mental health provider who minimizes addiction. Someone who holds both.',
      'Our integrated case management approach ensures that your treatment plan addresses substance use and mental health as interconnected — because they are. We coordinate providers, align treatment goals, and make sure nothing falls through the cracks between specialties.',
    ],
    whoItHelps: [
      'Individuals who have struggled with both addiction and mental health challenges',
      'People whose mental health symptoms have intensified with substance use',
      'Those who have been treated for one condition but not both',
      'Families navigating a loved one with a complex dual diagnosis',
      'Anyone who has had treatment fail because the full picture wasn\'t addressed',
    ],
    whatToExpect: [
      { title: 'Integrated Assessment', body: 'A comprehensive evaluation that examines both substance use and mental health simultaneously, identifying how each influences the other.' },
      { title: 'Unified Care Plan', body: 'A single, coordinated plan that addresses both conditions — not two separate plans that don\'t talk to each other.' },
      { title: 'Dual-Track Coordination', body: 'We manage relationships with providers across both specialties, ensuring they are aligned and communicating.' },
      { title: 'Ongoing Monitoring', body: 'We track progress across both dimensions and adjust the plan in real time as your needs change.' },
    ],
    differentiator: 'Co-occurring presentations are not a specialty add-on for us — they are the norm in the cases we see. Our clinical team is trained to hold both the substance use and the psychiatric complexity in view at all times, which is what effective dual-diagnosis care actually requires.',
  },
  {
    slug: 'intervention-services',
    num: '04',
    shortTitle: 'Clinical Intervention Services',
    title: 'Clinical Intervention Services',
    tagline: 'Interventions led by masters-level licensed clinicians — not just certified interventionists. When psychiatric complexity is part of the picture, clinical training isn\'t optional.',
    metaDescription: 'Masters-level clinical intervention services for substance use and mental health crises. Holistic Solutions provides licensed clinician-led interventions nationwide, including complex psychiatric cases.',
    keywords: 'clinical intervention services, masters level interventionist, addiction intervention Los Angeles, family intervention services, licensed clinician intervention, psychiatric intervention',
    overview: [
      'Most intervention services are led by certified interventionists — people trained in the process and structure of intervention. That training is valuable. But it has limits.',
      'When a loved one\'s mental health, trauma history, or psychiatric state is part of the picture — and it often is — you need someone who can read the room clinically. Someone who can recognize an emerging psychiatric crisis, respond to a trauma response in real time, and navigate complexity that goes beyond what a script can anticipate.',
      'Holistic Solutions interventions are led by licensed, masters-level clinicians. That distinction matters. We assess what\'s actually happening in the room, adapt in real time, and manage the full complexity of what unfolds — including immediate placement coordination when your loved one says yes.',
    ],
    whoItHelps: [
      'Families of someone who has refused help and needs structured support to accept it',
      'Situations involving co-occurring mental health and substance use',
      'Cases with trauma history or psychiatric complexity',
      'Families who have attempted an intervention before without success',
      'Situations requiring immediate placement following the intervention',
    ],
    whatToExpect: [
      { title: 'Pre-Intervention Planning', body: 'We work closely with the family to understand the full clinical picture, structure the intervention, and prepare everyone involved.' },
      { title: 'Clinical Facilitation', body: 'A licensed clinician leads the intervention — assessing what\'s happening in real time and guiding the process through complexity.' },
      { title: 'Immediate Placement', body: 'When your loved one agrees to get help, we move immediately. Treatment placement is coordinated in advance so there is no gap.' },
      { title: 'Family Support', body: 'We support the family throughout — before, during, and after — because intervention affects the whole system, not just the individual.' },
    ],
    differentiator: 'The difference between a certified interventionist and a licensed clinician is the difference between knowing the process and being clinically trained. When things go sideways — and in complex cases they often do — clinical training is what allows us to keep the intervention on track and keep everyone safe.',
  },
  {
    slug: 'treatment-placement',
    num: '05',
    shortTitle: 'Treatment Placement',
    title: 'Treatment Placement Services',
    tagline: 'We identify, vet, and place clients in the most appropriate programs nationwide. No guessing. No cold calls. The right fit, fast.',
    metaDescription: 'Expert treatment placement services for substance use and mental health nationwide. Holistic Solutions vets and places clients in detox, residential, PHP, IOP, and outpatient programs.',
    keywords: 'treatment placement services, find rehab nationwide, addiction treatment placement, residential treatment placement, detox placement, PHP IOP placement, behavioral health placement',
    overview: [
      'Searching for treatment on your own means cold-calling programs, navigating sales pitches, and trying to evaluate clinical quality without the knowledge to do it. It is exhausting — and the wrong placement costs time, money, and momentum.',
      'We have spent years building and vetting a national network of treatment programs across every level of care. We know which programs have strong clinical staff, which ones actually specialize in what your loved one is facing, and which ones to avoid. When we make a placement, it\'s purposeful — not random.',
      'Our placement process moves fast. When someone is ready for treatment, waiting is dangerous. We work quickly to identify the right options, verify insurance or arrange private pay, and get your loved one through the door with as little friction as possible.',
    ],
    whoItHelps: [
      'Individuals ready to enter treatment who don\'t know where to go',
      'Families overwhelmed by the number of options and the quality gap between programs',
      'People who have been to treatment before and need a better fit this time',
      'Cases requiring specialized programming — trauma, psychosis, dual diagnosis, executives',
      'Situations requiring immediate placement after an intervention or crisis',
    ],
    whatToExpect: [
      { title: 'Needs Assessment', body: 'We clarify clinical needs, budget, location preferences, and any special requirements before identifying programs.' },
      { title: 'Program Matching', body: 'We identify and present the best-fit options from our vetted national network — explaining the clinical rationale for each.' },
      { title: 'Insurance & Logistics', body: 'We verify coverage, handle pre-authorization, coordinate admissions, and manage the logistics of getting there.' },
      { title: 'Transition Support', body: 'Placement doesn\'t end at admission. We monitor progress and manage transitions through each level of care.' },
    ],
    differentiator: 'We have personally evaluated hundreds of programs. We do not refer from a list — we place with purpose, drawing on relationships and firsthand knowledge built over years of clinical work in this field.',
  },
  {
    slug: 'recovery-coaching',
    num: '06',
    shortTitle: 'Recovery Coaching',
    title: 'Recovery Coaching',
    tagline: 'Ongoing one-on-one coaching for individuals in active recovery — building the accountability, structure, and skills needed for lasting sobriety and mental wellness.',
    metaDescription: 'Professional recovery coaching and sober coaching services. Holistic Solutions provides one-on-one recovery support, accountability, and relapse prevention coaching nationwide.',
    keywords: 'recovery coaching, sober coaching, addiction recovery coach, relapse prevention coaching, sober support nationwide, recovery accountability coach',
    overview: [
      'Completing treatment is a milestone — not a finish line. The period immediately following discharge is often the highest-risk time in a person\'s recovery. Structure disappears, triggers reappear, and the support that existed in treatment is suddenly gone.',
      'Recovery coaching fills that gap. It is ongoing, one-on-one support from someone who knows recovery — its rhythms, its hard moments, and what it actually takes to build a life that works.',
      'Our coaching focuses on the practical: daily structure, accountability, skill-building, relapse prevention planning, and navigating the real-world challenges that arise in early and ongoing recovery. This is not therapy — it\'s active, in-your-corner support from someone invested in your success.',
    ],
    whoItHelps: [
      'Individuals newly out of residential treatment navigating the transition home',
      'People in early recovery who want accountability and structured support',
      'Those managing a high-stress professional life alongside sobriety',
      'Anyone who has relapsed and wants a stronger support structure this time',
      'Individuals in long-term recovery navigating a significant life change or stressor',
    ],
    whatToExpect: [
      { title: 'Initial Session', body: 'We establish recovery goals, identify high-risk situations, and build a personalized coaching plan tailored to your life.' },
      { title: 'Regular Check-ins', body: 'Consistent scheduled sessions to review progress, troubleshoot challenges, and reinforce accountability.' },
      { title: 'Real-Time Support', body: 'Access to your coach during high-risk moments — not just scheduled sessions.' },
      { title: 'Long-Term Planning', body: 'We help build the habits, relationships, and daily structures that support lasting sobriety — not just short-term stability.' },
    ],
    differentiator: 'Our coaching is grounded in clinical understanding. We are not simply cheerleaders — we understand the neuroscience of addiction, the patterns of relapse, and the clinical factors that make recovery sustainable. That knowledge shapes every coaching relationship.',
  },
  {
    slug: 'companionship-support',
    num: '07',
    shortTitle: 'Companionship & Support',
    title: 'Companionship & Support Services',
    tagline: 'In-person support during high-risk moments, treatment transitions, or whenever a trusted, clinical presence is needed most.',
    metaDescription: 'Clinical companionship and sober companion services. Holistic Solutions provides in-person support during treatment transitions and high-risk moments for individuals in recovery.',
    keywords: 'sober companion, clinical companion services, addiction companion, in-person recovery support, sober escort, companionship services behavioral health',
    overview: [
      'Some moments in recovery require a real, present human being — not a phone call, not a session. Transitioning out of treatment, navigating a high-risk environment, attending a triggering event, or simply getting through a hard day are situations where in-person support makes a real difference.',
      'Our companion services provide exactly that: a trained, clinically-informed individual who is physically present with your loved one when it matters most. This is not babysitting — it is active, thoughtful support from someone who understands what\'s at stake.',
      'Companion services can be standalone or integrated into a broader case management plan. Duration and frequency are tailored to the specific situation and level of support needed.',
    ],
    whoItHelps: [
      'Individuals transitioning out of residential treatment into a less structured environment',
      'People navigating early recovery in a high-risk social environment',
      'Families who need temporary in-person support for a loved one between placements',
      'Individuals attending high-stress events (family gatherings, work situations) in early recovery',
      'Anyone whose recovery plan requires a consistent, present support figure',
    ],
    whatToExpect: [
      { title: 'Needs Assessment', body: 'We clarify the situation, the risk level, and the type of support that\'s most appropriate.' },
      { title: 'Matched Support', body: 'We match you with a companion whose background fits your specific needs and personality.' },
      { title: 'Active Presence', body: 'Your companion is engaged and attentive — not just physically present. They understand what to watch for and how to respond.' },
      { title: 'Coordination', body: 'Companion services are coordinated with the broader care plan, with regular communication to the case management team.' },
    ],
    differentiator: 'Our companions are not simply sober individuals with lived experience. They are trained, clinically-supervised support professionals who understand the behavioral patterns, risks, and needs specific to the individuals they serve.',
  },
  {
    slug: 'safe-transport',
    num: '08',
    shortTitle: 'Safe & Clinical Transport',
    title: 'Safe & Clinical Transport',
    tagline: 'Supervised, compassionate transport to treatment facilities, appointments, and step-down programs — ensuring your loved one arrives safely and supported.',
    metaDescription: 'Safe and clinical transport services for individuals entering treatment or attending appointments. Holistic Solutions provides supervised, compassionate transport nationwide.',
    keywords: 'safe clinical transport, addiction transport services, escort to treatment, transport to rehab, clinical transport behavioral health, safe transport to detox',
    overview: [
      'Getting a loved one from agreement to admission is often harder than it sounds. The window between "yes" and arrival at a treatment facility is fragile — and the wrong transport experience can close it.',
      'Our clinical transport service bridges that gap. We provide supervised, compassionate transport to treatment facilities, medical appointments, and step-down programs — ensuring your loved one is supported throughout the journey, not just handed off at the door.',
      'Every transport is managed by a clinically-informed team member who understands how to hold space during this transition. We communicate with the receiving facility in advance, manage the logistics, and stay present until handoff is complete.',
    ],
    whoItHelps: [
      'Families whose loved one has agreed to treatment and needs support getting there',
      'Individuals who need transport to a facility in another city or state',
      'People transitioning between levels of care (residential to PHP, PHP to IOP)',
      'Situations where flying or driving alone would be clinically inadvisable',
      'Anyone whose safety or commitment to treatment could be at risk during transit',
    ],
    whatToExpect: [
      { title: 'Logistics Coordination', body: 'We coordinate all transportation logistics — flights, ground transport, and arrival timing — in advance with the receiving facility.' },
      { title: 'Clinical Escort', body: 'A trained team member accompanies your loved one throughout the journey, providing support and stability.' },
      { title: 'Communication', body: 'We keep the family informed throughout the transport and confirm safe arrival.' },
      { title: 'Seamless Handoff', body: 'We coordinate directly with the admissions team to ensure a smooth, supported transition into care.' },
    ],
    differentiator: 'Clinical transport is not a taxi service with good intentions. Our team understands that the window between agreement and admission is clinically significant — and we treat it that way. Every transport is handled with the same care we bring to every aspect of our work.',
  },
]

export function getServiceBySlug(slug) {
  return services.find((s) => s.slug === slug)
}
